package com.earthgame.idle.presentation.globe

import android.graphics.Bitmap
import kotlin.math.abs
import kotlin.math.max
import kotlin.math.min

/**
 * The Earth's surface, generated in code.
 *
 * ## Why it is generated rather than shipped
 *
 * An Earth texture is exactly the kind of asset whose licensing quietly goes
 * unrecorded — the repository already carries one such problem (see
 * `docs/ASSETS.md`) and this feature was not going to add another. Every pixel
 * the globe draws is computed here from data authored in this file, so the
 * artwork is unambiguously this project's own, there is no attribution to
 * carry, and the APK grows by a few kilobytes of Kotlin instead of a few
 * megabytes of PNG.
 *
 * ## What is authored and what is generated
 *
 * [CONTINENTS] is hand-authored: coarse outlines of the landmasses in degrees
 * of longitude and latitude, written for this project, accurate enough that the
 * planet reads as Earth at a glance and no more precise than that. Everything
 * else — coastline detail, terrain, ice, ocean depth, cloud cover — is
 * generated by blurring that outline and perturbing it with value noise.
 *
 * The result is deliberately a **stylised** Earth rather than a photographic
 * one, which is both the look the rest of the game has and the only honest
 * thing to claim for an outline this coarse.
 *
 * Generation costs tens of milliseconds and happens once, off the main thread —
 * see `GlobeSurface`.
 */
object EarthSurface {

    /** Equirectangular texture size. Ample for a globe a few hundred pixels across. */
    const val TEXTURE_WIDTH = 1024
    const val TEXTURE_HEIGHT = 512

    /** Resolution the authored outlines are rasterised at before being blurred and roughened. */
    private const val MASK_WIDTH = 288
    private const val MASK_HEIGHT = 144

    /**
     * Coarse continent outlines, as closed rings of `(longitude, latitude)` in
     * degrees. Authored for this project by eye against a world map; the
     * intent is recognisability, not cartography.
     */
    val CONTINENTS: List<List<Pair<Double, Double>>> = listOf(
        // Africa
        listOf(
            -17.0 to 21.0, -16.0 to 14.0, -13.0 to 9.0, -8.0 to 4.0, 0.0 to 5.0, 6.0 to 4.0,
            9.0 to 4.0, 10.0 to 0.0, 13.0 to -5.0, 12.0 to -12.0, 13.0 to -17.0, 15.0 to -22.0,
            18.0 to -29.0, 20.0 to -34.0, 26.0 to -34.0, 32.0 to -29.0, 34.0 to -25.0,
            36.0 to -20.0, 40.0 to -16.0, 41.0 to -11.0, 40.0 to -6.0, 42.0 to -1.0,
            48.0 to -2.0, 51.0 to 4.0, 48.0 to 10.0, 44.0 to 11.0, 43.0 to 12.0, 38.0 to 15.0,
            37.0 to 20.0, 34.0 to 26.0, 33.0 to 31.0, 25.0 to 32.0, 18.0 to 30.0, 11.0 to 33.0,
            10.0 to 37.0, 3.0 to 36.0, -2.0 to 35.0, -6.0 to 36.0, -10.0 to 31.0, -16.0 to 25.0,
        ),
        // Eurasia
        listOf(
            -10.0 to 36.0, -9.0 to 43.0, -2.0 to 44.0, -1.0 to 49.0, -5.0 to 49.0, 2.0 to 51.0,
            4.0 to 53.0, 8.0 to 54.0, 10.0 to 58.0, 13.0 to 55.0, 19.0 to 55.0, 22.0 to 57.0,
            25.0 to 60.0, 21.0 to 63.0, 18.0 to 66.0, 21.0 to 70.0, 28.0 to 71.0, 40.0 to 68.0,
            50.0 to 69.0, 60.0 to 70.0, 70.0 to 73.0, 80.0 to 74.0, 100.0 to 77.0,
            113.0 to 74.0, 127.0 to 73.0, 140.0 to 72.0, 155.0 to 71.0, 170.0 to 69.0,
            180.0 to 66.0, 180.0 to 62.0, 163.0 to 60.0, 157.0 to 54.0, 143.0 to 53.0,
            142.0 to 46.0, 135.0 to 44.0, 130.0 to 38.0, 122.0 to 31.0, 120.0 to 23.0,
            110.0 to 21.0, 107.0 to 11.0, 103.0 to 2.0, 100.0 to 6.0, 97.0 to 16.0,
            91.0 to 22.0, 89.0 to 21.0, 80.0 to 16.0, 77.0 to 8.0, 73.0 to 16.0, 69.0 to 23.0,
            62.0 to 25.0, 57.0 to 22.0, 50.0 to 29.0, 48.0 to 30.0, 44.0 to 38.0, 36.0 to 36.0,
            30.0 to 31.0, 34.0 to 31.0, 33.0 to 35.0, 27.0 to 37.0, 23.0 to 40.0, 17.0 to 39.0,
            13.0 to 45.0, 8.0 to 44.0, 3.0 to 43.0,
        ),
        // Greenland
        listOf(
            -45.0 to 83.0, -20.0 to 81.0, -19.0 to 75.0, -22.0 to 70.0, -30.0 to 68.0,
            -42.0 to 60.0, -52.0 to 63.0, -55.0 to 69.0, -65.0 to 76.0, -58.0 to 82.0,
        ),
        // North America
        listOf(
            -168.0 to 66.0, -160.0 to 70.0, -140.0 to 70.0, -125.0 to 70.0, -110.0 to 68.0,
            -95.0 to 68.0, -80.0 to 70.0, -68.0 to 60.0, -58.0 to 52.0, -55.0 to 47.0,
            -65.0 to 45.0, -70.0 to 42.0, -76.0 to 36.0, -81.0 to 31.0, -80.0 to 25.0,
            -84.0 to 30.0, -90.0 to 29.0, -97.0 to 26.0, -97.0 to 22.0, -92.0 to 18.0,
            -88.0 to 21.0, -87.0 to 16.0, -83.0 to 9.0, -78.0 to 8.0, -83.0 to 15.0,
            -95.0 to 16.0, -105.0 to 20.0, -110.0 to 24.0, -114.0 to 30.0, -118.0 to 34.0,
            -124.0 to 40.0, -124.0 to 48.0, -131.0 to 53.0, -140.0 to 60.0, -150.0 to 60.0,
            -158.0 to 57.0, -165.0 to 60.0,
        ),
        // South America
        listOf(
            -81.0 to 8.0, -76.0 to 9.0, -71.0 to 12.0, -62.0 to 11.0, -52.0 to 5.0,
            -50.0 to 0.0, -44.0 to -2.0, -35.0 to -6.0, -38.0 to -13.0, -40.0 to -21.0,
            -48.0 to -25.0, -53.0 to -33.0, -58.0 to -38.0, -62.0 to -40.0, -65.0 to -45.0,
            -68.0 to -52.0, -75.0 to -53.0, -74.0 to -45.0, -73.0 to -37.0, -71.0 to -30.0,
            -70.0 to -23.0, -70.0 to -18.0, -76.0 to -14.0, -81.0 to -6.0, -80.0 to 0.0,
            -78.0 to 3.0,
        ),
        // Australia
        listOf(
            114.0 to -22.0, 113.0 to -26.0, 115.0 to -34.0, 119.0 to -35.0, 125.0 to -33.0,
            131.0 to -32.0, 137.0 to -35.0, 141.0 to -38.0, 146.0 to -39.0, 150.0 to -37.0,
            153.0 to -29.0, 153.0 to -25.0, 148.0 to -20.0, 142.0 to -11.0, 136.0 to -12.0,
            131.0 to -11.0, 126.0 to -14.0, 121.0 to -20.0,
        ),
        // Antarctica
        listOf(
            -180.0 to -72.0, -160.0 to -78.0, -120.0 to -74.0, -90.0 to -73.0, -60.0 to -70.0,
            -45.0 to -78.0, -20.0 to -71.0, 10.0 to -70.0, 40.0 to -68.0, 70.0 to -68.0,
            100.0 to -66.0, 130.0 to -66.0, 160.0 to -72.0, 180.0 to -78.0, 180.0 to -90.0,
            -180.0 to -90.0,
        ),
        // New Guinea
        listOf(131.0 to -1.0, 141.0 to -3.0, 150.0 to -7.0, 147.0 to -9.0, 140.0 to -9.0, 132.0 to -6.0),
        // Borneo
        listOf(109.0 to 2.0, 117.0 to 4.0, 119.0 to 0.0, 117.0 to -4.0, 110.0 to -3.0),
        // Madagascar
        listOf(44.0 to -12.0, 50.0 to -15.0, 50.0 to -25.0, 45.0 to -25.0, 43.0 to -17.0),
        // Japan
        listOf(130.0 to 33.0, 136.0 to 36.0, 141.0 to 41.0, 145.0 to 44.0, 142.0 to 39.0, 137.0 to 35.0, 132.0 to 32.0),
        // The British Isles
        listOf(-6.0 to 50.0, -2.0 to 51.0, 0.0 to 53.0, -1.0 to 58.0, -5.0 to 58.0, -6.0 to 54.0),
        // Sumatra
        listOf(95.0 to 5.0, 99.0 to 3.0, 106.0 to -6.0, 103.0 to -5.0, 97.0 to 0.0),
        // Java
        listOf(105.0 to -6.0, 114.0 to -7.0, 114.0 to -9.0, 105.0 to -8.0),
        // New Zealand
        listOf(172.0 to -34.0, 178.0 to -38.0, 174.0 to -42.0, 167.0 to -46.0, 166.0 to -44.0, 172.0 to -40.0),
        // Iceland
        listOf(-24.0 to 65.0, -14.0 to 66.0, -14.0 to 63.0, -22.0 to 63.0),
        // The Philippines
        listOf(120.0 to 18.0, 124.0 to 13.0, 126.0 to 7.0, 122.0 to 6.0, 120.0 to 12.0),
        // Sulawesi
        listOf(119.0 to 1.0, 125.0 to 1.0, 125.0 to -5.0, 120.0 to -5.0),
        // Cuba and Hispaniola
        listOf(-85.0 to 22.0, -77.0 to 21.0, -70.0 to 19.0, -80.0 to 20.0),
        // Svalbard
        listOf(11.0 to 80.0, 28.0 to 80.0, 25.0 to 77.0, 13.0 to 77.0),
    )

    /**
     * The land/sea field the texture is painted from, at [TEXTURE_WIDTH] ×
     * [TEXTURE_HEIGHT].
     *
     * Values above 0.5 are land; how far above sets how far inland. Built by
     * rasterising [CONTINENTS] coarsely, blurring the result (wrapping in
     * longitude so the seam is invisible) and roughening the coastline with
     * fractal noise, which is what turns straight authored edges into something
     * that reads as a coast.
     */
    private fun buildLandField(width: Int, height: Int): FloatArray {
        val coarse = rasteriseContinents()
        val blurred = blurWrapping(coarse, MASK_WIDTH, MASK_HEIGHT, radius = 2)

        val field = FloatArray(width * height)
        for (y in 0 until height) {
            val v = (y + 0.5f) / height
            for (x in 0 until width) {
                val u = (x + 0.5f) / width
                val base = sampleBilinearWrapping(blurred, MASK_WIDTH, MASK_HEIGHT, u, v)
                // Coastline roughness. The noise is sampled at the texture's own
                // scale so the detail is finer than anything the outlines carry.
                val roughness = fractalNoise(u * 14f, v * 7f, seed = 1, octaves = 4, periodX = 14)
                field[y * width + x] = base + 0.34f * (roughness - 0.5f) * 2f
            }
        }
        return field
    }

    /** Point-in-polygon rasterisation of the authored outlines, with bounding-box culling. */
    private fun rasteriseContinents(): FloatArray {
        val bounds = CONTINENTS.map { ring ->
            var minLon = 180.0
            var maxLon = -180.0
            var minLat = 90.0
            var maxLat = -90.0
            for ((lon, lat) in ring) {
                minLon = min(minLon, lon); maxLon = max(maxLon, lon)
                minLat = min(minLat, lat); maxLat = max(maxLat, lat)
            }
            doubleArrayOf(minLon, maxLon, minLat, maxLat)
        }

        val mask = FloatArray(MASK_WIDTH * MASK_HEIGHT)
        for (y in 0 until MASK_HEIGHT) {
            val latitude = 90.0 - (y + 0.5) * 180.0 / MASK_HEIGHT
            for (x in 0 until MASK_WIDTH) {
                val longitude = -180.0 + (x + 0.5) * 360.0 / MASK_WIDTH
                var land = false
                for (index in CONTINENTS.indices) {
                    val box = bounds[index]
                    if (longitude < box[0] || longitude > box[1]) continue
                    if (latitude < box[2] || latitude > box[3]) continue
                    if (containsPoint(CONTINENTS[index], longitude, latitude)) {
                        land = true
                        break
                    }
                }
                if (land) mask[y * MASK_WIDTH + x] = 1f
            }
        }
        return mask
    }

    /** Standard even-odd crossing test on a closed ring. */
    private fun containsPoint(ring: List<Pair<Double, Double>>, x: Double, y: Double): Boolean {
        var inside = false
        var j = ring.size - 1
        for (i in ring.indices) {
            val (xi, yi) = ring[i]
            val (xj, yj) = ring[j]
            if ((yi > y) != (yj > y) && x < (xj - xi) * (y - yi) / (yj - yi) + xi) {
                inside = !inside
            }
            j = i
        }
        return inside
    }

    /** Separable box blur. Longitude wraps; latitude clamps. */
    private fun blurWrapping(source: FloatArray, width: Int, height: Int, radius: Int): FloatArray {
        val horizontal = FloatArray(source.size)
        val window = radius * 2 + 1
        for (y in 0 until height) {
            for (x in 0 until width) {
                var total = 0f
                for (offset in -radius..radius) {
                    val sx = ((x + offset) % width + width) % width
                    total += source[y * width + sx]
                }
                horizontal[y * width + x] = total / window
            }
        }
        val result = FloatArray(source.size)
        for (y in 0 until height) {
            for (x in 0 until width) {
                var total = 0f
                for (offset in -radius..radius) {
                    val sy = (y + offset).coerceIn(0, height - 1)
                    total += horizontal[sy * width + x]
                }
                result[y * width + x] = total / window
            }
        }
        return result
    }

    private fun sampleBilinearWrapping(
        source: FloatArray,
        width: Int,
        height: Int,
        u: Float,
        v: Float,
    ): Float {
        val fx = u * width - 0.5f
        val fy = (v * height - 0.5f).coerceIn(0f, height - 1.0001f)
        val x0 = kotlin.math.floor(fx).toInt()
        val y0 = kotlin.math.floor(fy).toInt()
        val tx = fx - x0
        val ty = fy - y0
        val x0w = ((x0 % width) + width) % width
        val x1w = (x0w + 1) % width
        val y0c = y0.coerceIn(0, height - 1)
        val y1c = (y0 + 1).coerceIn(0, height - 1)

        val a = source[y0c * width + x0w]
        val b = source[y0c * width + x1w]
        val c = source[y1c * width + x0w]
        val d = source[y1c * width + x1w]
        return (a * (1 - tx) + b * tx) * (1 - ty) + (c * (1 - tx) + d * tx) * ty
    }

    // ------------------------------------------------------------- painting --

    /**
     * The Earth's colour map.
     *
     * The palette is chosen to sit with the rest of the game's UI rather than
     * to match satellite imagery: saturated ocean, readable biome bands by
     * latitude, brightened relief, and ice that reaches down from both poles.
     */
    fun createEarthBitmap(
        width: Int = TEXTURE_WIDTH,
        height: Int = TEXTURE_HEIGHT,
    ): Bitmap {
        val field = buildLandField(width, height)
        val pixels = IntArray(width * height)

        for (y in 0 until height) {
            val v = (y + 0.5f) / height
            val latitude = 90f - v * 180f
            val absLatitude = abs(latitude)
            for (x in 0 until width) {
                val u = (x + 0.5f) / width
                val index = y * width + x
                val landness = field[index]

                pixels[index] = if (landness > 0.5f) {
                    val inland = ((landness - 0.5f) / 0.5f).coerceIn(0f, 1f)
                    val relief = fractalNoise(u * 26f, v * 13f, seed = 7, octaves = 4, periodX = 26)
                    landColour(absLatitude, inland, relief)
                } else {
                    val depth = ((0.5f - landness) / 0.5f).coerceIn(0f, 1f)
                    oceanColour(absLatitude, depth)
                }
            }
        }
        return Bitmap.createBitmap(pixels, width, height, Bitmap.Config.ARGB_8888)
    }

    private fun landColour(absLatitude: Float, inland: Float, relief: Float): Int {
        // Biome bands by latitude: rainforest, desert, temperate, boreal, tundra.
        val tropical = intArrayOf(0x2F, 0x7A, 0x3C)
        val arid = intArrayOf(0xC2, 0xA0, 0x5E)
        val temperate = intArrayOf(0x4A, 0x7C, 0x45)
        val boreal = intArrayOf(0x35, 0x5E, 0x45)
        val tundra = intArrayOf(0x8C, 0x93, 0x86)

        val base = when {
            absLatitude < 12f -> tropical
            absLatitude < 20f -> blend(tropical, arid, (absLatitude - 12f) / 8f)
            absLatitude < 32f -> arid
            absLatitude < 42f -> blend(arid, temperate, (absLatitude - 32f) / 10f)
            absLatitude < 54f -> temperate
            absLatitude < 64f -> blend(temperate, boreal, (absLatitude - 54f) / 10f)
            absLatitude < 70f -> blend(boreal, tundra, (absLatitude - 64f) / 6f)
            else -> tundra
        }

        // Relief lightens high ground and darkens basins, and drier interiors
        // pale off — enough shape that the land is not a flat wash.
        val shade = 0.82f + 0.36f * relief + 0.10f * inland
        var r = (base[0] * shade)
        var g = (base[1] * shade)
        var b = (base[2] * shade)

        // Permanent ice, reaching further at the poles.
        val ice = ((absLatitude - 66f) / 14f).coerceIn(0f, 1f)
        if (ice > 0f) {
            r = r * (1 - ice) + 0xF0 * ice
            g = g * (1 - ice) + 0xF6 * ice
            b = b * (1 - ice) + 0xFF * ice
        }
        return argb(r, g, b)
    }

    private fun oceanColour(absLatitude: Float, depth: Float): Int {
        val shallow = intArrayOf(0x2E, 0x86, 0xA8)
        val deep = intArrayOf(0x0B, 0x2C, 0x59)
        val base = blend(shallow, deep, smoothstep(depth))

        var r = base[0].toFloat()
        var g = base[1].toFloat()
        var b = base[2].toFloat()

        // Sea ice over the polar oceans.
        val ice = ((absLatitude - 72f) / 12f).coerceIn(0f, 1f)
        if (ice > 0f) {
            r = r * (1 - ice) + 0xDF * ice
            g = g * (1 - ice) + 0xEC * ice
            b = b * (1 - ice) + 0xF7 * ice
        }
        return argb(r, g, b)
    }

    /**
     * The cloud shell's alpha map.
     *
     * Banded by latitude to match the wind model's three cells — a wet band
     * over the equator, clear subtropics, a stormy mid-latitude belt — so the
     * clouds and the wind streamlines tell the same story. Fully transparent
     * where there is no cloud, so one texture serves every cloud coverage: the
     * shader scales its opacity by the simulated humidity rather than the
     * texture being regenerated.
     */
    fun createCloudBitmap(width: Int = 512, height: Int = 256): Bitmap {
        val pixels = IntArray(width * height)
        for (y in 0 until height) {
            val v = (y + 0.5f) / height
            val absLatitude = abs(90f - v * 180f)
            val band = when {
                absLatitude < 10f -> 1.0f
                absLatitude < 22f -> 1.0f - (absLatitude - 10f) / 12f * 0.75f
                absLatitude < 32f -> 0.25f
                absLatitude < 60f -> 0.25f + (absLatitude - 32f) / 28f * 0.7f
                else -> 0.95f - (absLatitude - 60f) / 30f * 0.35f
            }
            for (x in 0 until width) {
                val u = (x + 0.5f) / width
                val noise = fractalNoise(u * 10f, v * 5f, seed = 23, octaves = 5, periodX = 10)
                val density = ((noise - 0.42f) / 0.45f).coerceIn(0f, 1f) * band
                val alpha = (density * 255f).toInt().coerceIn(0, 255)
                pixels[y * width + x] = (alpha shl 24) or 0x00FFFFFF
            }
        }
        return Bitmap.createBitmap(pixels, width, height, Bitmap.Config.ARGB_8888)
    }

    // ---------------------------------------------------------------- noise --

    /**
     * Value noise, tiling in x so the texture has no seam at the date line.
     *
     * Value rather than gradient noise on purpose: it is a handful of integer
     * operations per sample, it is perfectly reproducible across devices
     * because nothing in it depends on a platform RNG, and at the scales used
     * here the difference is invisible.
     */
    private fun fractalNoise(x: Float, y: Float, seed: Int, octaves: Int, periodX: Int): Float {
        var total = 0f
        var amplitude = 1f
        var normaliser = 0f
        var frequency = 1f
        var period = periodX
        for (octave in 0 until octaves) {
            total += amplitude * valueNoise(x * frequency, y * frequency, seed + octave, period)
            normaliser += amplitude
            amplitude *= 0.5f
            frequency *= 2f
            period *= 2
        }
        return total / normaliser
    }

    private fun valueNoise(x: Float, y: Float, seed: Int, periodX: Int): Float {
        val x0 = kotlin.math.floor(x).toInt()
        val y0 = kotlin.math.floor(y).toInt()
        val tx = smoothstep(x - x0)
        val ty = smoothstep(y - y0)

        val a = hash(wrap(x0, periodX), y0, seed)
        val b = hash(wrap(x0 + 1, periodX), y0, seed)
        val c = hash(wrap(x0, periodX), y0 + 1, seed)
        val d = hash(wrap(x0 + 1, periodX), y0 + 1, seed)

        return (a * (1 - tx) + b * tx) * (1 - ty) + (c * (1 - tx) + d * tx) * ty
    }

    private fun wrap(value: Int, period: Int): Int = ((value % period) + period) % period

    private fun hash(x: Int, y: Int, seed: Int): Float {
        var h = x * 374761393 + y * 668265263 + seed * 1274126177
        h = (h xor (h shr 13)) * 1274126177
        h = h xor (h shr 16)
        return (h and 0x7FFFFFF).toFloat() / 0x7FFFFFF.toFloat()
    }

    private fun smoothstep(x: Float): Float {
        val t = x.coerceIn(0f, 1f)
        return t * t * (3f - 2f * t)
    }

    private fun blend(a: IntArray, b: IntArray, t: Float): IntArray {
        val k = t.coerceIn(0f, 1f)
        return intArrayOf(
            (a[0] + (b[0] - a[0]) * k).toInt(),
            (a[1] + (b[1] - a[1]) * k).toInt(),
            (a[2] + (b[2] - a[2]) * k).toInt(),
        )
    }

    private fun argb(r: Float, g: Float, b: Float): Int =
        (0xFF shl 24) or
            (r.toInt().coerceIn(0, 255) shl 16) or
            (g.toInt().coerceIn(0, 255) shl 8) or
            b.toInt().coerceIn(0, 255)
}
