/**
 * Spendable currencies, distinct from the atmospheric gases in `gases.ts`.
 * Gases are simulation state you drive up; resources are a balance you earn
 * and spend on technologies. New material resources can be added here
 * without touching engine code — technologies reference them by id.
 */
export type ResourceId = 'energy' | 'research' | 'coal' | 'oil' | 'steel' | 'concrete';

export interface ResourceDefinition {
  id: ResourceId;
  name: string;
  shortName: string;
  description: string;
}

export const RESOURCES: Record<ResourceId, ResourceDefinition> = {
  energy: {
    id: 'energy',
    name: 'Energy',
    shortName: 'Energy',
    description: 'The general economic/industrial currency. Most technologies are built with Energy.',
  },
  research: {
    id: 'research',
    name: 'Research',
    shortName: 'RP',
    description: 'Generated by your civilization\'s knowledge base. Spent to unlock new technology-tree nodes.',
  },
  coal: {
    id: 'coal',
    name: 'Coal',
    shortName: 'Coal',
    description: 'A mined material. Feeds early industrial and power technologies.',
  },
  oil: {
    id: 'oil',
    name: 'Oil',
    shortName: 'Oil',
    description: 'A drilled material. Feeds fossil-fuel, petrochemical and transportation technologies.',
  },
  steel: {
    id: 'steel',
    name: 'Steel',
    shortName: 'Steel',
    description: 'A refined material. Feeds construction and heavy-industry technologies.',
  },
  concrete: {
    id: 'concrete',
    name: 'Concrete',
    shortName: 'Concrete',
    description: 'A manufactured material. Feeds construction and urbanization technologies.',
  },
};

export const RESOURCE_LIST: ResourceDefinition[] = Object.values(RESOURCES);

export type ResourceBundle = Partial<Record<ResourceId, import('./bignum').Decimal>>;
