package com.earthgame.idle.domain.technologies

import com.earthgame.idle.domain.model.GasId
import com.earthgame.idle.domain.model.ResourceId

val AGRICULTURE_TECHS: List<Technology> = listOf(
    Technology(
        id = "farming",
        displayName = "Farming",
        branch = TechBranch.AGRICULTURE,
        kind = TechKind.GENERATOR,
        tier = 7,
        description = "Cleared and tilled fields feed more mouths than foraging ever could.",
        icon = "🌾",
        requires = listOf("early_agriculture"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(7))),
        costGrowth = generatorCostGrowth(7),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(7)),
            resourceProductionPerUnit = mapOf(ResourceId.ENERGY to resourceProduction(6), ResourceId.RESEARCH to resourceProduction(6)),
        ),
    ),
    Technology(
        id = "animal_domestication",
        displayName = "Animal Domestication",
        branch = TechBranch.AGRICULTURE,
        kind = TechKind.GENERATOR,
        tier = 8,
        description = "Herded livestock provide labor, meat, and milk — plus a lot of digestive methane.",
        icon = "🐄",
        requires = listOf("farming"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(8))),
        costGrowth = generatorCostGrowth(8),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CH4 to gasProduction(8), GasId.N2O to gasProduction(6) * 0.2),
            resourceProductionPerUnit = mapOf(ResourceId.ENERGY to resourceProduction(7), ResourceId.RESEARCH to resourceProduction(6)),
        ),
    ),
    Technology(
        id = "irrigation",
        displayName = "Irrigation",
        branch = TechBranch.AGRICULTURE,
        kind = TechKind.UNLOCK,
        tier = 9,
        description = "Channeling water to fields turns marginal land productive year-round.",
        icon = "💧",
        requires = listOf("farming"),
        cost = listOf(TechCost(ResourceId.RESEARCH, researchCost(9))),
        costGrowth = 1.0,
        maxOwned = 1,
        effect = TechEffect(
            researchMultiplier = 1.08,
        ),
    ),
    Technology(
        id = "rice_cultivation",
        displayName = "Rice Cultivation",
        branch = TechBranch.AGRICULTURE,
        kind = TechKind.GENERATOR,
        tier = 10,
        description = "Flooded paddies feed empires — and their waterlogged soil breeds methanogenic bacteria by the trillion.",
        icon = "🌾",
        requires = listOf("irrigation"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(10))),
        costGrowth = generatorCostGrowth(10),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CH4 to gasProduction(10), GasId.N2O to gasProduction(8) * 0.3),
        ),
    ),
    Technology(
        id = "livestock",
        displayName = "Livestock",
        branch = TechBranch.AGRICULTURE,
        kind = TechKind.GENERATOR,
        tier = 11,
        description = "Industrial-scale herding scales up meat production — and methane output — together.",
        icon = "🐑",
        requires = listOf("animal_domestication"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(11))),
        costGrowth = generatorCostGrowth(11),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CH4 to gasProduction(11), GasId.N2O to gasProduction(9) * 0.3),
            resourceProductionPerUnit = mapOf(ResourceId.ENERGY to resourceProduction(9)),
        ),
    ),
    Technology(
        id = "fertilizer",
        displayName = "Fertilizer",
        branch = TechBranch.AGRICULTURE,
        kind = TechKind.UNLOCK,
        tier = 12,
        description = "Manure and mineral amendments boost yields beyond what soil alone can sustain.",
        icon = "💩",
        requires = listOf("rice_cultivation", "livestock"),
        cost = listOf(TechCost(ResourceId.RESEARCH, researchCost(12))),
        costGrowth = 1.0,
        maxOwned = 1,
        effect = TechEffect(
            researchMultiplier = 1.1,
        ),
    ),
    Technology(
        id = "synthetic_fertilizer",
        displayName = "Synthetic Fertilizer",
        branch = TechBranch.AGRICULTURE,
        kind = TechKind.GENERATOR,
        tier = 13,
        description = "Haber-Bosch ammonia turns air into fertilizer, feeding billions — and flooding soils with nitrous oxide.",
        icon = "🧪",
        requires = listOf("fertilizer", "ammonia"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(13))),
        costGrowth = generatorCostGrowth(13),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.N2O to gasProduction(13)),
            resourceProductionPerUnit = mapOf(ResourceId.RESEARCH to resourceProduction(11)),
        ),
    ),
    Technology(
        id = "industrial_agriculture",
        displayName = "Industrial Agriculture",
        branch = TechBranch.AGRICULTURE,
        kind = TechKind.UNLOCK,
        tier = 14,
        description = "Mechanized planting, harvesting, and processing turn farming into heavy industry.",
        icon = "🚜",
        requires = listOf("synthetic_fertilizer"),
        cost = listOf(TechCost(ResourceId.RESEARCH, researchCost(14))),
        costGrowth = 1.0,
        maxOwned = 1,
        effect = TechEffect(
            branchProductionMultiplier = BranchMultiplier(TechBranch.AGRICULTURE, 1.3),
        ),
    ),
    Technology(
        id = "mega_farms",
        displayName = "Mega Farms",
        branch = TechBranch.AGRICULTURE,
        kind = TechKind.GENERATOR,
        tier = 15,
        description = "Horizon-spanning monocultures, fed and fertilized entirely by machine.",
        icon = "🌽",
        requires = listOf("industrial_agriculture"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(15))),
        costGrowth = generatorCostGrowth(15),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(14), GasId.CH4 to gasProduction(14), GasId.N2O to gasProduction(14)),
            resourceProductionPerUnit = mapOf(ResourceId.ENERGY to resourceProduction(13)),
        ),
    ),
    Technology(
        id = "factory_farming",
        displayName = "Factory Farming",
        branch = TechBranch.AGRICULTURE,
        kind = TechKind.GENERATOR,
        tier = 16,
        description = "Livestock raised at industrial density, on an industrial timetable.",
        icon = "🏚️",
        requires = listOf("mega_farms"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(16))),
        costGrowth = generatorCostGrowth(16),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CH4 to gasProduction(16), GasId.N2O to gasProduction(15)),
            resourceProductionPerUnit = mapOf(ResourceId.ENERGY to resourceProduction(14)),
        ),
    ),
)
