package com.earthgame.idle.domain.technologies

import com.earthgame.idle.domain.model.GasId
import com.earthgame.idle.domain.model.ResourceId

val CHEMISTRY_TECHS: List<Technology> = listOf(
    Technology(
        id = "industrial_chemistry",
        displayName = "Industrial Chemistry",
        branch = TechBranch.CHEMISTRY,
        kind = TechKind.UNLOCK,
        tier = 11,
        description = "Systematic chemistry turns raw materials into whatever industry needs next.",
        icon = "⚗️",
        requires = listOf("chemical_industry"),
        cost = listOf(TechCost(ResourceId.RESEARCH, researchCost(11))),
        costGrowth = 1.0,
        maxOwned = 1,
        effect = TechEffect(
            researchMultiplier = 1.1,
        ),
    ),
    Technology(
        id = "ammonia",
        displayName = "Ammonia",
        branch = TechBranch.CHEMISTRY,
        kind = TechKind.GENERATOR,
        tier = 12,
        description = "The Haber-Bosch process fixes nitrogen from thin air at industrial scale, feeding fertilizer plants worldwide.",
        icon = "🧪",
        requires = listOf("industrial_chemistry"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(12))),
        costGrowth = generatorCostGrowth(12),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.N2O to gasProduction(10) * 0.4),
            resourceProductionPerUnit = mapOf(ResourceId.ENERGY to resourceProduction(12)),
        ),
    ),
    Technology(
        id = "refrigeration",
        displayName = "Refrigeration",
        branch = TechBranch.CHEMISTRY,
        kind = TechKind.GENERATOR,
        tier = 14,
        description = "Mechanical cooling preserves food and comfort alike — using the first synthetic refrigerant gases.",
        icon = "🧊",
        requires = listOf("ammonia"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(14))),
        costGrowth = generatorCostGrowth(14),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.FLUORINATED to gasProduction(9) * 0.05),
            resourceProductionPerUnit = mapOf(ResourceId.ENERGY to resourceProduction(13)),
        ),
    ),
    Technology(
        id = "cfcs",
        displayName = "CFCs",
        branch = TechBranch.CHEMISTRY,
        kind = TechKind.GENERATOR,
        tier = 16,
        description = "Chlorofluorocarbons are cheap, stable, and everywhere — stable enough to drift into the stratosphere and eat ozone.",
        icon = "🌀",
        requires = listOf("refrigeration"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(16))),
        costGrowth = generatorCostGrowth(16),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.FLUORINATED to gasProduction(11) * 0.08),
            gasRemovalPerUnit = mapOf(GasId.O3 to gasProduction(9) * 0.05),
        ),
    ),
    Technology(
        id = "hfcs",
        displayName = "HFCs",
        branch = TechBranch.CHEMISTRY,
        kind = TechKind.GENERATOR,
        tier = 18,
        description = "Hydrofluorocarbons replace ozone-eating CFCs — leaving the ozone layer alone, and warming the planet directly instead.",
        icon = "🌀",
        requires = listOf("cfcs"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(18))),
        costGrowth = generatorCostGrowth(18),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.FLUORINATED to gasProduction(13) * 0.1),
        ),
    ),
    Technology(
        id = "industrial_fluorinated_gases",
        displayName = "Industrial Fluorinated Gases",
        branch = TechBranch.CHEMISTRY,
        kind = TechKind.GENERATOR,
        tier = 20,
        description = "PFCs and SF₆: some of the most potent, most persistent greenhouse gases ever synthesized.",
        icon = "☣️",
        requires = listOf("hfcs"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(20))),
        costGrowth = generatorCostGrowth(20),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.FLUORINATED to gasProduction(15) * 0.12),
        ),
    ),
    Technology(
        id = "advanced_chemical_manufacturing",
        displayName = "Advanced Chemical Manufacturing",
        branch = TechBranch.CHEMISTRY,
        kind = TechKind.MULTIPLIER,
        tier = 21,
        description = "Automated, continuous chemical plants run every reaction in this branch simultaneously, everywhere.",
        icon = "🏭",
        requires = listOf("industrial_fluorinated_gases"),
        cost = listOf(TechCost(ResourceId.ENERGY, unlockCost(21))),
        costGrowth = 1.0,
        maxOwned = 1,
        effect = TechEffect(
            globalProductionMultiplier = 1.35,
        ),
    ),
)
