package com.earthgame.idle.domain.technologies

import com.earthgame.idle.domain.model.GasId
import com.earthgame.idle.domain.model.ResourceId

val CONSTRUCTION_TECHS: List<Technology> = listOf(
    Technology(
        id = "concrete",
        displayName = "Concrete",
        branch = TechBranch.CONSTRUCTION,
        kind = TechKind.GENERATOR,
        tier = 11,
        description = "The most-used material on Earth, and one of the most carbon-intensive to produce.",
        icon = "🧱",
        requires = listOf("cement_production"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(11))),
        costGrowth = generatorCostGrowth(11),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(11)),
            resourceProductionPerUnit = mapOf(ResourceId.CONCRETE to resourceProduction(11)),
        ),
    ),
    Technology(
        id = "steel_buildings",
        displayName = "Steel Buildings",
        branch = TechBranch.CONSTRUCTION,
        kind = TechKind.GENERATOR,
        tier = 13,
        description = "Steel frames let buildings rise higher and faster than stone or wood ever allowed.",
        icon = "🏢",
        requires = listOf("steel_production", "concrete"),
        cost = listOf(TechCost(ResourceId.STEEL, generatorBaseCost(13))),
        costGrowth = generatorCostGrowth(13),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(13)),
            resourceProductionPerUnit = mapOf(ResourceId.ENERGY to resourceProduction(13)),
        ),
    ),
    Technology(
        id = "skyscrapers",
        displayName = "Skyscrapers",
        branch = TechBranch.CONSTRUCTION,
        kind = TechKind.GENERATOR,
        tier = 15,
        description = "Kilometer-scale towers pack a city's worth of energy demand onto one city block.",
        icon = "🏙️",
        requires = listOf("steel_buildings"),
        cost = listOf(TechCost(ResourceId.STEEL, generatorBaseCost(15))),
        costGrowth = generatorCostGrowth(15),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(15)),
            resourceProductionPerUnit = mapOf(ResourceId.ENERGY to resourceProduction(15)),
        ),
    ),
    Technology(
        id = "airports",
        displayName = "Airports",
        branch = TechBranch.CONSTRUCTION,
        kind = TechKind.GENERATOR,
        tier = 16,
        description = "Runways and terminals sprawl outward to keep pace with air travel demand.",
        icon = "🛬",
        requires = listOf("concrete", "commercial_aviation"),
        cost = listOf(TechCost(ResourceId.CONCRETE, generatorBaseCost(16))),
        costGrowth = generatorCostGrowth(16),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(15)),
            resourceProductionPerUnit = mapOf(ResourceId.ENERGY to resourceProduction(16)),
        ),
    ),
    Technology(
        id = "megacities",
        displayName = "Megacities",
        branch = TechBranch.CONSTRUCTION,
        kind = TechKind.GENERATOR,
        tier = 17,
        description = "Tens of millions of people, one continuous urban sprawl, running nonstop.",
        icon = "🌆",
        requires = listOf("skyscrapers"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(17))),
        costGrowth = generatorCostGrowth(17),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(17), GasId.CH4 to gasProduction(14)),
            resourceProductionPerUnit = mapOf(ResourceId.ENERGY to resourceProduction(17)),
        ),
    ),
    Technology(
        id = "mega_infrastructure",
        displayName = "Mega Infrastructure",
        branch = TechBranch.CONSTRUCTION,
        kind = TechKind.MULTIPLIER,
        tier = 18,
        description = "Nationwide grids, ports, and transit systems bind cities into a single machine.",
        icon = "🏗️",
        requires = listOf("megacities", "airports"),
        cost = listOf(TechCost(ResourceId.ENERGY, unlockCost(18))),
        costGrowth = 1.0,
        maxOwned = 1,
        effect = TechEffect(
            globalProductionMultiplier = 1.3,
        ),
    ),
    Technology(
        id = "global_urbanization",
        displayName = "Global Urbanization",
        branch = TechBranch.CONSTRUCTION,
        kind = TechKind.MULTIPLIER,
        tier = 19,
        description = "More than half the human race now lives in cities built this way. There is no going back.",
        icon = "🌍",
        requires = listOf("mega_infrastructure"),
        cost = listOf(TechCost(ResourceId.ENERGY, unlockCost(19))),
        costGrowth = 1.0,
        maxOwned = 1,
        effect = TechEffect(
            globalProductionMultiplier = 1.3,
            researchMultiplier = 1.2,
        ),
    ),
)
