package com.earthgame.idle.domain.technologies

import com.earthgame.idle.domain.model.GasId
import com.earthgame.idle.domain.model.ResourceId

val DIGITAL_TECHS: List<Technology> = listOf(
    Technology(
        id = "computers",
        displayName = "Computers",
        branch = TechBranch.DIGITAL,
        kind = TechKind.UNLOCK,
        tier = 20,
        description = "Electronic computation replaces rooms full of clerks with a single humming cabinet.",
        icon = "💻",
        requires = listOf("mass_electrification"),
        cost = listOf(TechCost(ResourceId.RESEARCH, researchCost(20))),
        costGrowth = 1.0,
        maxOwned = 1,
        effect = TechEffect(
            researchMultiplier = 1.3,
        ),
    ),
    Technology(
        id = "internet",
        displayName = "Internet",
        branch = TechBranch.DIGITAL,
        kind = TechKind.MULTIPLIER,
        tier = 22,
        description = "A global network lets every computer, factory, and market talk to every other, instantly.",
        icon = "🌐",
        requires = listOf("computers", "global_supply_chains"),
        cost = listOf(TechCost(ResourceId.ENERGY, unlockCost(22))),
        costGrowth = 1.0,
        maxOwned = 1,
        effect = TechEffect(
            researchMultiplier = 1.4,
            globalProductionMultiplier = 1.1,
        ),
    ),
    Technology(
        id = "data_centers",
        displayName = "Data Centers",
        branch = TechBranch.DIGITAL,
        kind = TechKind.GENERATOR,
        tier = 23,
        description = "Warehouses of servers run around the clock, drawing enormous power to keep the internet online.",
        icon = "🖥️",
        requires = listOf("internet"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(23))),
        costGrowth = generatorCostGrowth(23),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(23)),
            resourceProductionPerUnit = mapOf(ResourceId.RESEARCH to resourceProduction(21)),
        ),
    ),
    Technology(
        id = "cloud_computing",
        displayName = "Cloud Computing",
        branch = TechBranch.DIGITAL,
        kind = TechKind.GENERATOR,
        tier = 24,
        description = "Computation-as-a-service means every phone and laptop can now offload work to a distant, power-hungry server farm.",
        icon = "☁️",
        requires = listOf("data_centers"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(24))),
        costGrowth = generatorCostGrowth(24),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(24)),
            resourceProductionPerUnit = mapOf(ResourceId.RESEARCH to resourceProduction(23)),
        ),
    ),
    Technology(
        id = "ai",
        displayName = "AI",
        branch = TechBranch.DIGITAL,
        kind = TechKind.GENERATOR,
        tier = 25,
        description = "Machine learning models train on oceans of data, accelerating research — and power demand — together.",
        icon = "🤖",
        requires = listOf("cloud_computing"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(25))),
        costGrowth = generatorCostGrowth(25),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(25)),
            resourceProductionPerUnit = mapOf(ResourceId.RESEARCH to resourceProduction(24)),
        ),
    ),
    Technology(
        id = "mass_ai_infrastructure",
        displayName = "Mass AI Infrastructure",
        branch = TechBranch.DIGITAL,
        kind = TechKind.GENERATOR,
        tier = 26,
        description = "Entire power grids are now built specifically to feed AI training clusters.",
        icon = "🧠",
        requires = listOf("ai"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(26))),
        costGrowth = generatorCostGrowth(26),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(26)),
            resourceProductionPerUnit = mapOf(ResourceId.RESEARCH to resourceProduction(25), ResourceId.ENERGY to resourceProduction(24)),
        ),
    ),
    Technology(
        id = "hyperscale_data_centers",
        displayName = "Hyperscale Data Centers",
        branch = TechBranch.DIGITAL,
        kind = TechKind.MULTIPLIER,
        tier = 27,
        description = "Campuses of data centers the size of small cities, humming continuously, forever.",
        icon = "🏢",
        requires = listOf("mass_ai_infrastructure"),
        cost = listOf(TechCost(ResourceId.ENERGY, unlockCost(27))),
        costGrowth = 1.0,
        maxOwned = 1,
        effect = TechEffect(
            globalProductionMultiplier = 1.6,
            researchMultiplier = 1.5,
        ),
    ),
)
