package com.earthgame.idle.domain.technologies

import com.earthgame.idle.domain.model.GasId
import com.earthgame.idle.domain.model.ResourceId

val ELECTRICITY_TECHS: List<Technology> = listOf(
    Technology(
        id = "generator_dynamo",
        displayName = "Generator",
        branch = TechBranch.ELECTRICITY,
        kind = TechKind.GENERATOR,
        tier = 9,
        description = "Spinning a coil in a magnetic field conjures current from motion.",
        icon = "🔌",
        requires = listOf("steam_engine"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(9))),
        costGrowth = generatorCostGrowth(9),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(7)),
            resourceProductionPerUnit = mapOf(ResourceId.ENERGY to resourceProduction(9)),
        ),
    ),
    Technology(
        id = "coal_power_plant",
        displayName = "Coal Power Plant",
        branch = TechBranch.ELECTRICITY,
        kind = TechKind.GENERATOR,
        tier = 11,
        description = "Burning coal to boil water to spin turbines: the workhorse of the industrial grid.",
        icon = "🏭",
        requires = listOf("generator_dynamo", "coal_mining"),
        cost = listOf(
            TechCost(ResourceId.ENERGY, generatorBaseCost(11)),
            TechCost(ResourceId.COAL, generatorBaseCost(10)),
        ),
        costGrowth = generatorCostGrowth(11),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(11)),
            resourceProductionPerUnit = mapOf(ResourceId.ENERGY to resourceProduction(12)),
        ),
    ),
    Technology(
        id = "grid_electricity",
        displayName = "Grid Electricity",
        branch = TechBranch.ELECTRICITY,
        kind = TechKind.MULTIPLIER,
        tier = 12,
        description = "A unified transmission grid lets every factory and home run on demand.",
        icon = "🗲",
        requires = listOf("coal_power_plant"),
        cost = listOf(TechCost(ResourceId.ENERGY, unlockCost(12))),
        costGrowth = 1.0,
        maxOwned = 1,
        effect = TechEffect(
            globalProductionMultiplier = 1.2,
        ),
    ),
    Technology(
        id = "hydroelectricity",
        displayName = "Hydroelectricity",
        branch = TechBranch.ELECTRICITY,
        kind = TechKind.GENERATOR,
        tier = 13,
        description = "Dammed rivers spin turbines with no combustion at all — clean, steady, huge.",
        icon = "🌊",
        requires = listOf("grid_electricity"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(13))),
        costGrowth = generatorCostGrowth(13),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(6)),
            resourceProductionPerUnit = mapOf(ResourceId.ENERGY to resourceProduction(13)),
        ),
    ),
    Technology(
        id = "gas_turbine",
        displayName = "Gas Turbine",
        branch = TechBranch.ELECTRICITY,
        kind = TechKind.GENERATOR,
        tier = 13,
        description = "Burning natural gas spins a turbine directly — quicker to build, dirtier than hydro.",
        icon = "🔥",
        requires = listOf("grid_electricity"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(13))),
        costGrowth = generatorCostGrowth(13),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(12)),
            resourceProductionPerUnit = mapOf(ResourceId.ENERGY to resourceProduction(13)),
        ),
    ),
    Technology(
        id = "coal_industrialization",
        displayName = "Coal Industrialization",
        branch = TechBranch.ELECTRICITY,
        kind = TechKind.CHOICE,
        tier = 14,
        description = "Double down on cheap, abundant coal. Energy is plentiful; emissions skyrocket.",
        icon = "⚫",
        requires = listOf("coal_power_plant"),
        cost = listOf(TechCost(ResourceId.ENERGY, unlockCost(14))),
        costGrowth = 1.0,
        maxOwned = 1,
        choiceGroup = "energy_strategy",
        effect = TechEffect(
            gasProductionMultiplier = GasMultiplier(GasId.CO2, 10.0),
        ),
    ),
    Technology(
        id = "nuclear_industrialization",
        displayName = "Nuclear Industrialization",
        branch = TechBranch.ELECTRICITY,
        kind = TechKind.CHOICE,
        tier = 14,
        description = "Invest in expensive, complex nuclear infrastructure for enormous clean output.",
        icon = "☢️",
        requires = listOf("coal_power_plant"),
        cost = listOf(TechCost(ResourceId.ENERGY, unlockCost(14) * 1.5)),
        costGrowth = 1.0,
        maxOwned = 1,
        choiceGroup = "energy_strategy",
        effect = TechEffect(
            resourceProductionMultiplier = ResourceMultiplier(ResourceId.ENERGY, 5.0),
        ),
    ),
    Technology(
        id = "nuclear_power",
        displayName = "Nuclear Power",
        branch = TechBranch.ELECTRICITY,
        kind = TechKind.GENERATOR,
        tier = 15,
        description = "Splitting atoms releases enormous energy with almost no direct emissions.",
        icon = "☢️",
        requires = listOf("grid_electricity"),
        cost = listOf(
            TechCost(ResourceId.ENERGY, generatorBaseCost(15)),
            TechCost(ResourceId.STEEL, generatorBaseCost(13)),
        ),
        costGrowth = generatorCostGrowth(15),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(4)),
            resourceProductionPerUnit = mapOf(ResourceId.ENERGY to resourceProduction(15)),
        ),
    ),
    Technology(
        id = "supercritical_coal",
        displayName = "Supercritical Coal",
        branch = TechBranch.ELECTRICITY,
        kind = TechKind.GENERATOR,
        tier = 16,
        description = "Higher pressures and temperatures wring more power from every lump of coal — and more CO₂.",
        icon = "🏭",
        requires = listOf("coal_power_plant"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(16))),
        costGrowth = generatorCostGrowth(16),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(16)),
            resourceProductionPerUnit = mapOf(ResourceId.ENERGY to resourceProduction(16)),
        ),
    ),
    Technology(
        id = "combined_cycle_gas",
        displayName = "Combined Cycle Gas",
        branch = TechBranch.ELECTRICITY,
        kind = TechKind.GENERATOR,
        tier = 16,
        description = "Pairing a gas turbine with a steam turbine squeezes far more energy from the same fuel.",
        icon = "🔧",
        requires = listOf("gas_turbine"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(16))),
        costGrowth = generatorCostGrowth(16),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(15)),
            resourceProductionPerUnit = mapOf(ResourceId.ENERGY to resourceProduction(17)),
        ),
    ),
    Technology(
        id = "mass_electrification",
        displayName = "Mass Electrification",
        branch = TechBranch.ELECTRICITY,
        kind = TechKind.MULTIPLIER,
        tier = 17,
        description = "Every corner of civilization now runs on the grid. Output compounds everywhere.",
        icon = "⚡",
        requires = listOf("nuclear_power", "combined_cycle_gas"),
        cost = listOf(TechCost(ResourceId.ENERGY, unlockCost(17))),
        costGrowth = 1.0,
        maxOwned = 1,
        effect = TechEffect(
            globalProductionMultiplier = 1.3,
        ),
    ),
)
