package com.earthgame.idle.domain.technologies

import com.earthgame.idle.domain.model.GasId
import com.earthgame.idle.domain.model.ResourceId

val FOSSIL_FUEL_TECHS: List<Technology> = listOf(
    Technology(
        id = "oil_drilling",
        displayName = "Oil Drilling",
        branch = TechBranch.FOSSIL_FUELS,
        kind = TechKind.GENERATOR,
        tier = 9,
        description = "Derricks tap ancient buried hydrocarbons — denser energy than coal, easier to move.",
        icon = "🛢️",
        requires = listOf("steam_engine"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(9))),
        costGrowth = generatorCostGrowth(9),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(7)),
            resourceProductionPerUnit = mapOf(ResourceId.OIL to resourceProduction(9)),
        ),
    ),
    Technology(
        id = "oil_refinery",
        displayName = "Oil Refinery",
        branch = TechBranch.FOSSIL_FUELS,
        kind = TechKind.GENERATOR,
        tier = 10,
        description = "Cracking crude into fuel and feedstock unlocks everything downstream of petroleum.",
        icon = "🏭",
        requires = listOf("oil_drilling"),
        cost = listOf(
            TechCost(ResourceId.ENERGY, generatorBaseCost(10)),
            TechCost(ResourceId.OIL, generatorBaseCost(9)),
        ),
        costGrowth = generatorCostGrowth(10),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(10)),
            resourceProductionPerUnit = mapOf(ResourceId.ENERGY to resourceProduction(10)),
        ),
    ),
    Technology(
        id = "petrochemicals",
        displayName = "Petrochemicals",
        branch = TechBranch.FOSSIL_FUELS,
        kind = TechKind.UNLOCK,
        tier = 12,
        description = "Oil becomes plastic, solvent, and synthetic fiber. Petroleum touches everything now.",
        icon = "⚗️",
        requires = listOf("oil_refinery"),
        cost = listOf(TechCost(ResourceId.RESEARCH, generatorBaseCost(12) * 0.4)),
        costGrowth = 1.0,
        maxOwned = 1,
        effect = TechEffect(
            researchMultiplier = 1.1,
        ),
    ),
    Technology(
        id = "natural_gas",
        displayName = "Natural Gas",
        branch = TechBranch.FOSSIL_FUELS,
        kind = TechKind.GENERATOR,
        tier = 12,
        description = "Gas burns cleaner than coal, per unit of energy — though it still adds up fast at scale.",
        icon = "🔥",
        requires = listOf("oil_drilling"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(12))),
        costGrowth = generatorCostGrowth(12),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(11)),
            resourceProductionPerUnit = mapOf(ResourceId.ENERGY to resourceProduction(12)),
        ),
    ),
    Technology(
        id = "fracking",
        displayName = "Fracking",
        branch = TechBranch.FOSSIL_FUELS,
        kind = TechKind.GENERATOR,
        tier = 14,
        description = "Shattering deep shale releases trapped gas — and lets a fair amount of methane leak straight to the air.",
        icon = "💥",
        requires = listOf("natural_gas"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(14))),
        costGrowth = generatorCostGrowth(14),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(13), GasId.CH4 to gasProduction(11) * 0.4),
            resourceProductionPerUnit = mapOf(ResourceId.OIL to resourceProduction(13)),
        ),
    ),
    Technology(
        id = "offshore_drilling",
        displayName = "Offshore Drilling",
        branch = TechBranch.FOSSIL_FUELS,
        kind = TechKind.GENERATOR,
        tier = 15,
        description = "Platforms far out to sea reach reserves no derrick on land ever could.",
        icon = "🌊",
        requires = listOf("oil_refinery"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(15))),
        costGrowth = generatorCostGrowth(15),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(14)),
            resourceProductionPerUnit = mapOf(ResourceId.OIL to resourceProduction(15)),
        ),
    ),
    Technology(
        id = "oil_sands",
        displayName = "Oil Sands",
        branch = TechBranch.FOSSIL_FUELS,
        kind = TechKind.GENERATOR,
        tier = 16,
        description = "Extracting oil from tar-thick sand takes enormous heat and water — and emits accordingly.",
        icon = "🏜️",
        requires = listOf("offshore_drilling"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(16))),
        costGrowth = generatorCostGrowth(16),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(16) * 1.3),
            resourceProductionPerUnit = mapOf(ResourceId.OIL to resourceProduction(16)),
        ),
    ),
    Technology(
        id = "coal_mega_mining",
        displayName = "Coal Mega-Mining",
        branch = TechBranch.FOSSIL_FUELS,
        kind = TechKind.GENERATOR,
        tier = 17,
        description = "Whole mountains are leveled for the coal seams beneath them.",
        icon = "⛏️",
        requires = listOf("coal_mining", "oil_sands"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(17))),
        costGrowth = generatorCostGrowth(17),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(17)),
            resourceProductionPerUnit = mapOf(ResourceId.COAL to resourceProduction(17)),
        ),
    ),
)
