package com.earthgame.idle.domain.technologies

import com.earthgame.idle.domain.model.GasId
import com.earthgame.idle.domain.model.ResourceId

val GLOBALIZATION_TECHS: List<Technology> = listOf(
    Technology(
        id = "international_trade",
        displayName = "International Trade",
        branch = TechBranch.GLOBALIZATION,
        kind = TechKind.UNLOCK,
        tier = 17,
        description = "Nations specialize and trade at scale, wiring the world's economies together.",
        icon = "🌐",
        requires = listOf("container_ships"),
        cost = listOf(TechCost(ResourceId.RESEARCH, researchCost(17))),
        costGrowth = 1.0,
        maxOwned = 1,
        effect = TechEffect(
            researchMultiplier = 1.15,
        ),
    ),
    Technology(
        id = "containerization",
        displayName = "Containerization",
        branch = TechBranch.GLOBALIZATION,
        kind = TechKind.GENERATOR,
        tier = 18,
        description = "Standardized shipping containers make loading and moving goods almost frictionless — so the world moves a lot more of them.",
        icon = "📦",
        requires = listOf("international_trade"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(18))),
        costGrowth = generatorCostGrowth(18),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(17)),
            resourceProductionPerUnit = mapOf(ResourceId.ENERGY to resourceProduction(18)),
        ),
    ),
    Technology(
        id = "global_supply_chains",
        displayName = "Global Supply Chains",
        branch = TechBranch.GLOBALIZATION,
        kind = TechKind.MULTIPLIER,
        tier = 19,
        description = "Parts cross a dozen borders before a product is finished. Efficiency has no geography left.",
        icon = "🔗",
        requires = listOf("containerization", "global_logistics"),
        cost = listOf(TechCost(ResourceId.ENERGY, unlockCost(19))),
        costGrowth = 1.0,
        maxOwned = 1,
        effect = TechEffect(
            globalProductionMultiplier = 1.25,
        ),
    ),
    Technology(
        id = "consumer_economy",
        displayName = "Consumer Economy",
        branch = TechBranch.GLOBALIZATION,
        kind = TechKind.GENERATOR,
        tier = 20,
        description = "Mass production meets mass marketing: an economy built on buying more, replacing sooner, discarding faster.",
        icon = "🛍️",
        requires = listOf("global_supply_chains"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(20))),
        costGrowth = generatorCostGrowth(20),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(20), GasId.CH4 to gasProduction(16)),
            resourceProductionPerUnit = mapOf(ResourceId.ENERGY to resourceProduction(20)),
        ),
    ),
    Technology(
        id = "global_aviation_networks",
        displayName = "Global Aviation Networks",
        branch = TechBranch.GLOBALIZATION,
        kind = TechKind.GENERATOR,
        tier = 21,
        description = "Hub airports link every major city on the planet with a same-day flight.",
        icon = "🛩️",
        requires = listOf("commercial_aviation"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(21))),
        costGrowth = generatorCostGrowth(21),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(21), GasId.O3 to gasProduction(13) * 0.2),
            resourceProductionPerUnit = mapOf(ResourceId.ENERGY to resourceProduction(21)),
        ),
    ),
    Technology(
        id = "247_manufacturing",
        displayName = "24/7 Manufacturing",
        branch = TechBranch.GLOBALIZATION,
        kind = TechKind.GENERATOR,
        tier = 22,
        description = "Factories across every time zone mean production never actually stops, anywhere, ever.",
        icon = "🏭",
        requires = listOf("consumer_economy"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(22))),
        costGrowth = generatorCostGrowth(22),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(22)),
            resourceProductionPerUnit = mapOf(ResourceId.ENERGY to resourceProduction(22)),
        ),
    ),
    Technology(
        id = "megacorporations",
        displayName = "Megacorporations",
        branch = TechBranch.GLOBALIZATION,
        kind = TechKind.MULTIPLIER,
        tier = 23,
        description = "A handful of firms now operate at the scale of nations, and answer to no single one.",
        icon = "🏢",
        requires = listOf("247_manufacturing", "global_aviation_networks"),
        cost = listOf(TechCost(ResourceId.ENERGY, unlockCost(23))),
        costGrowth = 1.0,
        maxOwned = 1,
        effect = TechEffect(
            globalProductionMultiplier = 1.5,
            researchMultiplier = 1.3,
        ),
    ),
)
