package com.earthgame.idle.domain.technologies

import com.earthgame.idle.domain.model.GasId
import com.earthgame.idle.domain.model.ResourceId

val INDUSTRY_TECHS: List<Technology> = listOf(
    Technology(
        id = "steam_engine",
        displayName = "Steam Engine",
        branch = TechBranch.INDUSTRY,
        kind = TechKind.UNLOCK,
        tier = 8,
        description = "Boiling water under pressure yields mechanical power on demand. The industrial age begins.",
        icon = "⚙️",
        requires = listOf("iron"),
        cost = listOf(TechCost(ResourceId.RESEARCH, researchCost(8))),
        costGrowth = 1.0,
        maxOwned = 1,
    ),
    Technology(
        id = "coal_mining",
        displayName = "Coal Mining",
        branch = TechBranch.INDUSTRY,
        kind = TechKind.GENERATOR,
        tier = 9,
        description = "Deep shafts pull ancient buried carbon out of the ground by the wagonload.",
        icon = "⛏️",
        requires = listOf("steam_engine"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(9))),
        costGrowth = generatorCostGrowth(9),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(8)),
            resourceProductionPerUnit = mapOf(ResourceId.COAL to resourceProduction(9)),
        ),
    ),
    Technology(
        id = "steam_locomotive",
        displayName = "Steam Locomotive",
        branch = TechBranch.INDUSTRY,
        kind = TechKind.GENERATOR,
        tier = 10,
        description = "Rail networks haul coal and freight faster than any road ever could.",
        icon = "🚂",
        requires = listOf("coal_mining"),
        cost = listOf(
            TechCost(ResourceId.ENERGY, generatorBaseCost(10)),
            TechCost(ResourceId.COAL, generatorBaseCost(8)),
        ),
        costGrowth = generatorCostGrowth(10),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(10)),
            resourceProductionPerUnit = mapOf(ResourceId.ENERGY to resourceProduction(9)),
        ),
    ),
    Technology(
        id = "factories",
        displayName = "Factories",
        branch = TechBranch.INDUSTRY,
        kind = TechKind.GENERATOR,
        tier = 11,
        description = "Coal-fired machinery under one roof outproduces a hundred workshops.",
        icon = "🏭",
        requires = listOf("steam_engine"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(11))),
        costGrowth = generatorCostGrowth(11),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(11)),
            resourceProductionPerUnit = mapOf(ResourceId.ENERGY to resourceProduction(11)),
        ),
    ),
    Technology(
        id = "steel_production",
        displayName = "Steel Production",
        branch = TechBranch.INDUSTRY,
        kind = TechKind.GENERATOR,
        tier = 12,
        description = "Bessemer converters turn iron into steel at unprecedented volume.",
        icon = "🔩",
        requires = listOf("coal_mining", "iron"),
        cost = listOf(
            TechCost(ResourceId.ENERGY, generatorBaseCost(12)),
            TechCost(ResourceId.COAL, generatorBaseCost(10)),
        ),
        costGrowth = generatorCostGrowth(12),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(12)),
            resourceProductionPerUnit = mapOf(ResourceId.STEEL to resourceProduction(11)),
        ),
    ),
    Technology(
        id = "cement_production",
        displayName = "Cement Production",
        branch = TechBranch.INDUSTRY,
        kind = TechKind.GENERATOR,
        tier = 12,
        description = "Roasting limestone into clinker is one of the most carbon-intensive processes in industry.",
        icon = "🧱",
        requires = listOf("factories"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(12))),
        costGrowth = generatorCostGrowth(12),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(12) * 1.4),
            resourceProductionPerUnit = mapOf(ResourceId.CONCRETE to resourceProduction(11)),
        ),
    ),
    Technology(
        id = "industrial_furnaces",
        displayName = "Industrial Furnaces",
        branch = TechBranch.INDUSTRY,
        kind = TechKind.GENERATOR,
        tier = 13,
        description = "Ever-hotter furnaces process ore, scrap, and fuel around the clock.",
        icon = "🔥",
        requires = listOf("steel_production"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(13))),
        costGrowth = generatorCostGrowth(13),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(13)),
            resourceProductionPerUnit = mapOf(ResourceId.STEEL to resourceProduction(12)),
        ),
    ),
    Technology(
        id = "mass_manufacturing",
        displayName = "Mass Manufacturing",
        branch = TechBranch.INDUSTRY,
        kind = TechKind.MULTIPLIER,
        tier = 14,
        description = "Standardized parts and assembly lines multiply every factory's output at once.",
        icon = "📦",
        requires = listOf("factories", "cement_production"),
        cost = listOf(TechCost(ResourceId.ENERGY, unlockCost(14))),
        costGrowth = 1.0,
        maxOwned = 1,
        effect = TechEffect(
            globalProductionMultiplier = 1.25,
        ),
    ),
    Technology(
        id = "chemical_industry",
        displayName = "Chemical Industry",
        branch = TechBranch.INDUSTRY,
        kind = TechKind.UNLOCK,
        tier = 15,
        description = "Industrial-scale chemistry opens doors nature never built.",
        icon = "⚗️",
        requires = listOf("mass_manufacturing"),
        cost = listOf(TechCost(ResourceId.RESEARCH, researchCost(15))),
        costGrowth = 1.0,
        maxOwned = 1,
    ),
)
