package com.earthgame.idle.domain.technologies

import com.earthgame.idle.domain.model.GasId
import com.earthgame.idle.domain.model.ResourceId

/**
 * Extraction: the bottom of every production chain.
 *
 * Nothing in this branch consumes anything. These are the buildings that pull
 * raw material out of the planet and hand it to the processors, and the reason
 * the rest of the economy has anything to work with. Their reward for scale is
 * also the game's clearest lesson in consequences: every one of them emits, and
 * the ore they feed to a mill emits again on the way through.
 */
val MINING_TECHS: List<Technology> = listOf(
    Technology(
        id = "surface_prospecting",
        displayName = "Surface Prospecting",
        branch = TechBranch.MINING,
        kind = TechKind.UNLOCK,
        tier = 8,
        description = "Systematic searching for ore bodies instead of stumbling across them. Opens deliberate mining.",
        icon = "🧭",
        requires = listOf("metalworking"),
        cost = listOf(TechCost(ResourceId.RESEARCH, researchCost(8))),
        costGrowth = 1.0,
        maxOwned = 1,
        effect = TechEffect(researchMultiplier = 1.1),
    ),
    Technology(
        id = "iron_mining",
        displayName = "Iron Mine",
        branch = TechBranch.MINING,
        kind = TechKind.GENERATOR,
        tier = 9,
        description = "An open seam worked for ore. Iron Ore is worth nothing on its own — a mill has to turn it into Metals.",
        icon = "⛏️",
        requires = listOf("surface_prospecting"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(9))),
        costGrowth = generatorCostGrowth(9),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(8)),
            resourceProductionPerUnit = mapOf(ResourceId.IRON to resourceProduction(10)),
        ),
    ),
    Technology(
        id = "copper_mining",
        displayName = "Copper Mine",
        branch = TechBranch.MINING,
        kind = TechKind.GENERATOR,
        tier = 11,
        description = "Copper is what a grid is made of, and later what a circuit board is made of. Mine it before you need it.",
        icon = "🟠",
        requires = listOf("iron_mining"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(11))),
        costGrowth = generatorCostGrowth(11),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(10)),
            resourceProductionPerUnit = mapOf(ResourceId.COPPER to resourceProduction(11)),
        ),
    ),
    Technology(
        id = "mechanised_mining",
        displayName = "Mechanised Mining",
        branch = TechBranch.MINING,
        kind = TechKind.MULTIPLIER,
        tier = 12,
        description = "Draglines and haul trucks replace pick and shovel. +60% to everything this branch digs up.",
        icon = "🚜",
        requires = listOf("copper_mining", "steam_engine"),
        cost = listOf(TechCost(ResourceId.ENERGY, unlockCost(12))),
        costGrowth = 1.0,
        maxOwned = 1,
        effect = TechEffect(branchProductionMultiplier = BranchMultiplier(TechBranch.MINING, 1.6)),
    ),
    Technology(
        id = "open_pit_mining",
        displayName = "Open-Pit Mining",
        branch = TechBranch.MINING,
        kind = TechKind.GENERATOR,
        tier = 14,
        description = "A hole visible from orbit. Ore grade falls, volume more than makes up for it, and the landscape does not come back.",
        icon = "🕳️",
        requires = listOf("mechanised_mining"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(14))),
        costGrowth = generatorCostGrowth(14),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(14)),
            resourceProductionPerUnit = mapOf(
                ResourceId.IRON to resourceProduction(14),
                ResourceId.COPPER to resourceProduction(13),
            ),
        ),
    ),
    Technology(
        id = "uranium_prospecting",
        displayName = "Uranium Prospecting",
        branch = TechBranch.MINING,
        kind = TechKind.UNLOCK,
        tier = 16,
        description = "Geiger counters over the desert. Finding the ore is the easy half of nuclear power.",
        icon = "📻",
        requires = listOf("open_pit_mining", "nuclear_power"),
        cost = listOf(TechCost(ResourceId.RESEARCH, researchCost(15))),
        costGrowth = 1.0,
        maxOwned = 1,
    ),
    Technology(
        id = "uranium_mining",
        displayName = "Uranium Mine",
        branch = TechBranch.MINING,
        kind = TechKind.GENERATOR,
        tier = 17,
        description = "Yellowcake out of the ground. A tonne of it holds more energy than a trainload of coal — and releases none of the carbon.",
        icon = "☢️",
        requires = listOf("uranium_prospecting"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(16))),
        costGrowth = generatorCostGrowth(16),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(14)),
            resourceProductionPerUnit = mapOf(ResourceId.URANIUM to resourceProduction(16)),
        ),
    ),
    Technology(
        id = "rare_earth_processing",
        displayName = "Rare Earth Processing",
        branch = TechBranch.MINING,
        kind = TechKind.UNLOCK,
        tier = 17,
        description = "Separating seventeen chemically near-identical metals. Miserable, filthy, and the whole of modern electronics depends on it.",
        icon = "🧫",
        requires = listOf("open_pit_mining", "industrial_chemistry"),
        cost = listOf(TechCost(ResourceId.RESEARCH, researchCost(17))),
        costGrowth = 1.0,
        maxOwned = 1,
    ),
    Technology(
        id = "rare_earth_mining",
        displayName = "Rare Earth Mine",
        branch = TechBranch.MINING,
        kind = TechKind.GENERATOR,
        tier = 18,
        description = "Tonnes of rock for kilograms of neodymium, and a tailings pond nobody wants to talk about.",
        icon = "💠",
        requires = listOf("rare_earth_processing"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(18))),
        costGrowth = generatorCostGrowth(18),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(17)),
            resourceProductionPerUnit = mapOf(ResourceId.RARE_EARTHS to resourceProduction(18)),
        ),
    ),
    Technology(
        id = "in_situ_leaching",
        displayName = "In-Situ Leaching",
        branch = TechBranch.MINING,
        kind = TechKind.GENERATOR,
        tier = 20,
        description = "Pump solvent down, pump dissolved metal up, never open a pit at all. Cheap, efficient, and the aquifer pays for it.",
        icon = "💧",
        requires = listOf("rare_earth_mining", "petrochemicals"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(20))),
        costGrowth = generatorCostGrowth(20),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(19)),
            resourceProductionPerUnit = mapOf(
                ResourceId.URANIUM to resourceProduction(19),
                ResourceId.COPPER to resourceProduction(20),
            ),
        ),
    ),
    Technology(
        id = "deep_sea_mining",
        displayName = "Deep-Sea Mining",
        branch = TechBranch.MINING,
        kind = TechKind.GENERATOR,
        tier = 23,
        description = "Nodules hoovered off the abyssal plain. The ecosystem being stirred into the water column took four million years to settle.",
        icon = "🌊",
        requires = listOf("in_situ_leaching", "containerization"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(23))),
        costGrowth = generatorCostGrowth(23),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(22)),
            resourceProductionPerUnit = mapOf(
                ResourceId.RARE_EARTHS to resourceProduction(23),
                ResourceId.IRON to resourceProduction(22),
            ),
        ),
    ),
    Technology(
        id = "autonomous_mining_fleets",
        displayName = "Autonomous Mining Fleets",
        branch = TechBranch.MINING,
        kind = TechKind.MULTIPLIER,
        tier = 26,
        description = "Nobody underground, nobody in the cab, nobody to send home at the end of a shift. ×2.5 to all extraction.",
        icon = "🤖",
        requires = listOf("deep_sea_mining", "ai"),
        cost = listOf(TechCost(ResourceId.ENERGY, unlockCost(26))),
        costGrowth = 1.0,
        maxOwned = 1,
        effect = TechEffect(branchProductionMultiplier = BranchMultiplier(TechBranch.MINING, 2.5)),
    ),
)
