package com.earthgame.idle.domain.technologies

import com.earthgame.idle.domain.model.GasId
import com.earthgame.idle.domain.model.ResourceId

val TRANSPORTATION_TECHS: List<Technology> = listOf(
    Technology(
        id = "horse_and_cart",
        displayName = "Horse & Cart",
        branch = TechBranch.TRANSPORTATION,
        kind = TechKind.GENERATOR,
        tier = 8,
        description = "Domesticated draft animals move goods faster than any human back.",
        icon = "🐴",
        requires = listOf("early_agriculture"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(8))),
        costGrowth = generatorCostGrowth(8),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CH4 to gasProduction(6) * 0.3),
            resourceProductionPerUnit = mapOf(ResourceId.RESEARCH to resourceProduction(7)),
        ),
    ),
    Technology(
        id = "steam_vehicle",
        displayName = "Steam Vehicle",
        branch = TechBranch.TRANSPORTATION,
        kind = TechKind.GENERATOR,
        tier = 10,
        description = "Self-propelled steam carriages replace the horse on the open road.",
        icon = "🚃",
        requires = listOf("steam_engine"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(10))),
        costGrowth = generatorCostGrowth(10),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(9)),
            resourceProductionPerUnit = mapOf(ResourceId.ENERGY to resourceProduction(9)),
        ),
    ),
    Technology(
        id = "automobile",
        displayName = "Automobile",
        branch = TechBranch.TRANSPORTATION,
        kind = TechKind.GENERATOR,
        tier = 12,
        description = "The internal combustion engine puts a private vehicle within reach of ordinary people.",
        icon = "🚗",
        requires = listOf("oil_refinery"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(12))),
        costGrowth = generatorCostGrowth(12),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(11)),
            resourceProductionPerUnit = mapOf(ResourceId.ENERGY to resourceProduction(11)),
        ),
    ),
    Technology(
        id = "mass_production_cars",
        displayName = "Mass Production Cars",
        branch = TechBranch.TRANSPORTATION,
        kind = TechKind.GENERATOR,
        tier = 13,
        description = "Assembly lines put a car in every driveway, and exhaust over every street.",
        icon = "🚙",
        requires = listOf("automobile", "factories"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(13))),
        costGrowth = generatorCostGrowth(13),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(13)),
            resourceProductionPerUnit = mapOf(ResourceId.ENERGY to resourceProduction(12)),
        ),
    ),
    Technology(
        id = "diesel_engine",
        displayName = "Diesel Engine",
        branch = TechBranch.TRANSPORTATION,
        kind = TechKind.GENERATOR,
        tier = 13,
        description = "More torque, more efficiency, more soot — diesel becomes the standard for heavy hauling.",
        icon = "⛽",
        requires = listOf("oil_refinery"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(13))),
        costGrowth = generatorCostGrowth(13),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(12)),
            resourceProductionPerUnit = mapOf(ResourceId.ENERGY to resourceProduction(13)),
        ),
    ),
    Technology(
        id = "trucks",
        displayName = "Trucks",
        branch = TechBranch.TRANSPORTATION,
        kind = TechKind.GENERATOR,
        tier = 14,
        description = "Diesel freight trucks connect factories to shelves without needing a railway.",
        icon = "🚚",
        requires = listOf("diesel_engine"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(14))),
        costGrowth = generatorCostGrowth(14),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(14)),
            resourceProductionPerUnit = mapOf(ResourceId.ENERGY to resourceProduction(14)),
        ),
    ),
    Technology(
        id = "highways",
        displayName = "Highways",
        branch = TechBranch.TRANSPORTATION,
        kind = TechKind.MULTIPLIER,
        tier = 14,
        description = "Paved, limited-access roads let vehicles move faster, farther, and in far greater numbers.",
        icon = "🛣️",
        requires = listOf("mass_production_cars"),
        cost = listOf(TechCost(ResourceId.CONCRETE, unlockCost(14))),
        costGrowth = 1.0,
        maxOwned = 1,
        effect = TechEffect(
            branchProductionMultiplier = BranchMultiplier(TechBranch.TRANSPORTATION, 1.25),
        ),
    ),
    Technology(
        id = "jet_aircraft",
        displayName = "Jet Aircraft",
        branch = TechBranch.TRANSPORTATION,
        kind = TechKind.GENERATOR,
        tier = 15,
        description = "Turbojets cross continents in hours, burning fuel at high altitude where it matters more.",
        icon = "✈️",
        requires = listOf("diesel_engine", "petrochemicals"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(15))),
        costGrowth = generatorCostGrowth(15),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(15), GasId.N2O to gasProduction(11) * 0.15),
            resourceProductionPerUnit = mapOf(ResourceId.ENERGY to resourceProduction(15)),
        ),
    ),
    Technology(
        id = "commercial_aviation",
        displayName = "Commercial Aviation",
        branch = TechBranch.TRANSPORTATION,
        kind = TechKind.GENERATOR,
        tier = 16,
        description = "Air travel becomes routine, not remarkable. The skies fill with contrails.",
        icon = "🛫",
        requires = listOf("jet_aircraft"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(16))),
        costGrowth = generatorCostGrowth(16),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(16), GasId.O3 to gasProduction(10) * 0.2),
            resourceProductionPerUnit = mapOf(ResourceId.ENERGY to resourceProduction(16)),
        ),
    ),
    Technology(
        id = "container_ships",
        displayName = "Container Ships",
        branch = TechBranch.TRANSPORTATION,
        kind = TechKind.GENERATOR,
        tier = 16,
        description = "Standardized steel boxes on diesel-burning giants move the world's goods across oceans.",
        icon = "🚢",
        requires = listOf("oil_refinery"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(16))),
        costGrowth = generatorCostGrowth(16),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(15)),
            resourceProductionPerUnit = mapOf(ResourceId.ENERGY to resourceProduction(17)),
        ),
    ),
    Technology(
        id = "global_logistics",
        displayName = "Global Logistics",
        branch = TechBranch.TRANSPORTATION,
        kind = TechKind.MULTIPLIER,
        tier = 17,
        description = "Trucks, trains, ships, and planes now form one coordinated worldwide supply machine.",
        icon = "🌐",
        requires = listOf("container_ships", "trucks"),
        cost = listOf(TechCost(ResourceId.ENERGY, unlockCost(17))),
        costGrowth = 1.0,
        maxOwned = 1,
        effect = TechEffect(
            globalProductionMultiplier = 1.2,
        ),
    ),
    Technology(
        id = "supersonic_aviation",
        displayName = "Supersonic Aviation",
        branch = TechBranch.TRANSPORTATION,
        kind = TechKind.GENERATOR,
        tier = 19,
        description = "Breaking the sound barrier for a business flight, at an enormous fuel and emissions premium.",
        icon = "🚀",
        requires = listOf("commercial_aviation"),
        cost = listOf(TechCost(ResourceId.ENERGY, generatorBaseCost(19))),
        costGrowth = generatorCostGrowth(19),
        maxOwned = Technology.UNLIMITED,
        effect = TechEffect(
            gasProductionPerUnit = mapOf(GasId.CO2 to gasProduction(19), GasId.N2O to gasProduction(14) * 0.2),
            resourceProductionPerUnit = mapOf(ResourceId.ENERGY to resourceProduction(18)),
        ),
    ),
)
