package com.earthgame.idle.domain.model

/**
 * How a resource behaves in the production economy. Purely descriptive — the
 * class groups a resource for the UI and for the economy validator, and never
 * changes the arithmetic.
 *
 * See `docs/wiki/Economy-and-Production.md`.
 */
enum class ResourceClass(val id: String, val displayName: String) {
    /** Dug, drilled or pumped straight out of the planet. No inputs. */
    RAW("raw", "Raw materials"),

    /** Made by a processor out of raw materials. */
    PROCESSED("processed", "Processed materials"),

    /** Made out of processed materials — the top of the material chain. */
    ADVANCED("advanced", "Advanced materials"),

    /** The universal industrial currency, produced by nearly everything. */
    ENERGY("energy", "Energy"),

    /**
     * Not part of resource flow in the ordinary sense: never an input to a
     * processor, only ever earned and spent. Research is the tree's currency;
     * Earth Points live outside [ResourceId] entirely.
     */
    SPECIAL("special", "Special"),
}

/**
 * Spendable currencies, distinct from the atmospheric gases in [GasId]. Gases
 * are simulation state you drive up; resources are a balance you earn and
 * spend on technologies — and, since the production-chain economy, a *flow*
 * that processors consume.
 *
 * The persisted id strings match the reference implementation's for the six
 * resources that existed before the production chains. Every id here is a save
 * key: **never rename one**, and add new entries only at the end of the enum,
 * since [ResourceAmounts] indexes by ordinal.
 */
enum class ResourceId(val id: String) {
    ENERGY("energy"),
    RESEARCH("research"),
    COAL("coal"),
    OIL("oil"),

    /**
     * Player-facing name: **Metals**. The persisted id stays `"steel"` — it is
     * what every save ever written contains, and renaming it would strand a
     * player's balance for a cosmetic change. The enum constant keeps the id's
     * spelling for the same reason: the two have to be read together.
     */
    STEEL("steel"),
    CONCRETE("concrete"),

    // --- Added with the production-chain economy. Appended, never inserted. ---
    IRON("iron"),
    COPPER("copper"),
    URANIUM("uranium"),
    RARE_EARTHS("rare_earths"),
    FUEL("fuel"),
    CHEMICALS("chemicals"),
    ELECTRONICS("electronics"),
    ADVANCED_MATERIALS("advanced_materials"),
    LAUNCH_CAPACITY("launch_capacity");

    companion object {
        fun fromId(id: String): ResourceId? = entries.firstOrNull { it.id == id }
    }
}

data class ResourceDefinition(
    val id: ResourceId,
    val displayName: String,
    val shortName: String,
    val description: String,
    val resourceClass: ResourceClass = ResourceClass.SPECIAL,
    /**
     * Set when a resource is deliberately allowed to have no processor
     * consuming it. Every other resource must feed something, or
     * `validateEconomy` reports it as a dead end.
     */
    val deadEndReason: String? = null,
)

val RESOURCES: Map<ResourceId, ResourceDefinition> = listOf(
    ResourceDefinition(
        ResourceId.ENERGY, "Energy", "Energy",
        "The general economic/industrial currency. Most technologies are built with Energy.",
        ResourceClass.ENERGY,
    ),
    ResourceDefinition(
        ResourceId.RESEARCH, "Research", "RP",
        "Generated by your civilization's knowledge base. Spent to unlock new technology-tree nodes.",
        ResourceClass.SPECIAL,
        deadEndReason = "Research is the technology tree's currency. It is spent, never processed.",
    ),
    ResourceDefinition(
        ResourceId.COAL, "Coal", "Coal",
        "A mined material. Feeds early industrial and power technologies.",
        ResourceClass.RAW,
    ),
    ResourceDefinition(
        ResourceId.OIL, "Oil", "Oil",
        "A drilled material. Feeds fossil-fuel, petrochemical and transportation technologies.",
        ResourceClass.RAW,
    ),
    ResourceDefinition(
        ResourceId.STEEL, "Metals", "Metals",
        "Refined metals — iron, steel, aluminium, copper. Feed construction and heavy-industry technologies.",
        ResourceClass.PROCESSED,
    ),
    ResourceDefinition(
        ResourceId.CONCRETE, "Concrete", "Concrete",
        "A manufactured material. Feeds construction and urbanization technologies.",
        ResourceClass.PROCESSED,
        deadEndReason = "Concrete is a pure building material: it is spent on construction, never " +
            "fed back into a processor.",
    ),
    ResourceDefinition(
        ResourceId.IRON, "Iron Ore", "Iron",
        "Raw ore straight out of the ground. Worthless until a mill turns it into Metals.",
        ResourceClass.RAW,
    ),
    ResourceDefinition(
        ResourceId.COPPER, "Copper", "Copper",
        "Drawn into the wire that every grid and every circuit board is made of.",
        ResourceClass.RAW,
    ),
    ResourceDefinition(
        ResourceId.URANIUM, "Uranium", "Uranium",
        "Heavy, radioactive ore. Feeds fission reactors, which produce energy without carbon.",
        ResourceClass.RAW,
    ),
    ResourceDefinition(
        ResourceId.RARE_EARTHS, "Rare Earths", "REE",
        "Neodymium, dysprosium and the rest — tiny quantities, enormous leverage over electronics.",
        ResourceClass.RAW,
    ),
    ResourceDefinition(
        ResourceId.FUEL, "Refined Fuel", "Fuel",
        "Petrol, diesel and kerosene cracked out of crude. Burns hotter and moves further than what it came from.",
        ResourceClass.PROCESSED,
    ),
    ResourceDefinition(
        ResourceId.CHEMICALS, "Chemicals", "Chem",
        "Industrial feedstock: solvents, polymers, ammonia, fertiliser. The input half of modern manufacturing.",
        ResourceClass.PROCESSED,
    ),
    ResourceDefinition(
        ResourceId.ELECTRONICS, "Electronics", "Elec",
        "Chips, boards and controllers. Everything automated is built on top of them.",
        ResourceClass.ADVANCED,
    ),
    ResourceDefinition(
        ResourceId.ADVANCED_MATERIALS, "Advanced Materials", "AdvMat",
        "Superalloys, composites and engineered ceramics that survive conditions ordinary Metals cannot.",
        ResourceClass.ADVANCED,
    ),
    ResourceDefinition(
        ResourceId.LAUNCH_CAPACITY, "Launch Capacity", "Launch",
        "Tonnage to orbit per second. The gateway resource for everything the civilization builds off-planet.",
        ResourceClass.ADVANCED,
    ),
).associateBy { it.id }

val RESOURCE_LIST: List<ResourceDefinition> = ResourceId.entries.map { RESOURCES.getValue(it) }

fun resourceOf(id: ResourceId): ResourceDefinition = RESOURCES.getValue(id)

/** Resources of one class, in enum order. The Production screen's grouping. */
fun resourcesOfClass(resourceClass: ResourceClass): List<ResourceDefinition> =
    RESOURCE_LIST.filter { it.resourceClass == resourceClass }
