package com.earthgame.idle.domain.model

/**
 * Spendable currencies, distinct from the atmospheric gases in [GasId]. Gases
 * are simulation state you drive up; resources are a balance you earn and
 * spend on technologies.
 *
 * The persisted id strings match the reference implementation's.
 */
enum class ResourceId(val id: String) {
    ENERGY("energy"),
    RESEARCH("research"),
    COAL("coal"),
    OIL("oil"),

    /**
     * Player-facing name: **Metals**. The persisted id stays `"steel"` — it is
     * what every save ever written contains, and renaming it would strand a
     * player's balance for a cosmetic change. The enum constant keeps the id's
     * spelling for the same reason: the two have to be read together.
     */
    STEEL("steel"),
    CONCRETE("concrete");

    companion object {
        fun fromId(id: String): ResourceId? = entries.firstOrNull { it.id == id }
    }
}

data class ResourceDefinition(
    val id: ResourceId,
    val displayName: String,
    val shortName: String,
    val description: String,
)

val RESOURCES: Map<ResourceId, ResourceDefinition> = listOf(
    ResourceDefinition(
        ResourceId.ENERGY, "Energy", "Energy",
        "The general economic/industrial currency. Most technologies are built with Energy.",
    ),
    ResourceDefinition(
        ResourceId.RESEARCH, "Research", "RP",
        "Generated by your civilization's knowledge base. Spent to unlock new technology-tree nodes.",
    ),
    ResourceDefinition(
        ResourceId.COAL, "Coal", "Coal",
        "A mined material. Feeds early industrial and power technologies.",
    ),
    ResourceDefinition(
        ResourceId.OIL, "Oil", "Oil",
        "A drilled material. Feeds fossil-fuel, petrochemical and transportation technologies.",
    ),
    ResourceDefinition(
        ResourceId.STEEL, "Metals", "Metals",
        "Refined metals — iron, steel, aluminium, copper. Feed construction and heavy-industry technologies.",
    ),
    ResourceDefinition(
        ResourceId.CONCRETE, "Concrete", "Concrete",
        "A manufactured material. Feeds construction and urbanization technologies.",
    ),
).associateBy { it.id }

val RESOURCE_LIST: List<ResourceDefinition> = ResourceId.entries.map { RESOURCES.getValue(it) }

fun resourceOf(id: ResourceId): ResourceDefinition = RESOURCES.getValue(id)
