import { Technology } from './types';
import { researchCost, generatorBaseCost, gasProduction, resourceProduction, generatorCostGrowth } from './scaling';

export const AGRICULTURE_TECHS: Technology[] = [
  {
    id: 'farming',
    name: 'Farming',
    branch: 'agriculture',
    kind: 'generator',
    tier: 7,
    description: 'Cleared and tilled fields feed more mouths than foraging ever could.',
    icon: '🌾',
    requires: ['early_agriculture'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(7) }],
    costGrowth: generatorCostGrowth(7),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(7) },
      resourceProductionPerUnit: { research: resourceProduction(6) },
    },
  },
  {
    id: 'animal_domestication',
    name: 'Animal Domestication',
    branch: 'agriculture',
    kind: 'generator',
    tier: 8,
    description: 'Herded livestock provide labor, meat, and milk — plus a lot of digestive methane.',
    icon: '🐄',
    requires: ['farming'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(8) }],
    costGrowth: generatorCostGrowth(8),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { ch4: gasProduction(8), n2o: gasProduction(6) * 0.2 },
      resourceProductionPerUnit: { research: resourceProduction(6) },
    },
  },
  {
    id: 'irrigation',
    name: 'Irrigation',
    branch: 'agriculture',
    kind: 'unlock',
    tier: 9,
    description: 'Channeling water to fields turns marginal land productive year-round.',
    icon: '💧',
    requires: ['farming'],
    cost: [{ resource: 'research', baseAmount: researchCost(9) }],
    costGrowth: 1,
    maxOwned: 1,
    effect: { researchMultiplier: 1.08 },
  },
  {
    id: 'rice_cultivation',
    name: 'Rice Cultivation',
    branch: 'agriculture',
    kind: 'generator',
    tier: 10,
    description: 'Flooded paddies feed empires — and their waterlogged soil breeds methanogenic bacteria by the trillion.',
    icon: '🌾',
    requires: ['irrigation'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(10) }],
    costGrowth: generatorCostGrowth(10),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { ch4: gasProduction(10), n2o: gasProduction(8) * 0.3 },
    },
  },
  {
    id: 'livestock',
    name: 'Livestock',
    branch: 'agriculture',
    kind: 'generator',
    tier: 11,
    description: 'Industrial-scale herding scales up meat production — and methane output — together.',
    icon: '🐑',
    requires: ['animal_domestication'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(11) }],
    costGrowth: generatorCostGrowth(11),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { ch4: gasProduction(11), n2o: gasProduction(9) * 0.3 },
      resourceProductionPerUnit: { energy: resourceProduction(9) },
    },
  },
  {
    id: 'fertilizer',
    name: 'Fertilizer',
    branch: 'agriculture',
    kind: 'unlock',
    tier: 12,
    description: 'Manure and mineral amendments boost yields beyond what soil alone can sustain.',
    icon: '💩',
    requires: ['rice_cultivation', 'livestock'],
    cost: [{ resource: 'research', baseAmount: researchCost(12) }],
    costGrowth: 1,
    maxOwned: 1,
    effect: { researchMultiplier: 1.1 },
  },
  {
    id: 'synthetic_fertilizer',
    name: 'Synthetic Fertilizer',
    branch: 'agriculture',
    kind: 'generator',
    tier: 13,
    description: 'Haber-Bosch ammonia turns air into fertilizer, feeding billions — and flooding soils with nitrous oxide.',
    icon: '🧪',
    requires: ['fertilizer', 'ammonia'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(13) }],
    costGrowth: generatorCostGrowth(13),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { n2o: gasProduction(13) },
      resourceProductionPerUnit: { research: resourceProduction(11) },
    },
  },
  {
    id: 'industrial_agriculture',
    name: 'Industrial Agriculture',
    branch: 'agriculture',
    kind: 'unlock',
    tier: 14,
    description: 'Mechanized planting, harvesting, and processing turn farming into heavy industry.',
    icon: '🚜',
    requires: ['synthetic_fertilizer'],
    cost: [{ resource: 'research', baseAmount: researchCost(14) }],
    costGrowth: 1,
    maxOwned: 1,
    effect: { branchProductionMultiplier: { branch: 'agriculture', multiplier: 1.3 } },
  },
  {
    id: 'mega_farms',
    name: 'Mega Farms',
    branch: 'agriculture',
    kind: 'generator',
    tier: 15,
    description: 'Horizon-spanning monocultures, fed and fertilized entirely by machine.',
    icon: '🌽',
    requires: ['industrial_agriculture'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(15) }],
    costGrowth: generatorCostGrowth(15),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(14), ch4: gasProduction(14), n2o: gasProduction(14) },
      resourceProductionPerUnit: { energy: resourceProduction(13) },
    },
  },
  {
    id: 'factory_farming',
    name: 'Factory Farming',
    branch: 'agriculture',
    kind: 'generator',
    tier: 16,
    description: 'Livestock raised at industrial density, on an industrial timetable.',
    icon: '🏚️',
    requires: ['mega_farms'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(16) }],
    costGrowth: generatorCostGrowth(16),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { ch4: gasProduction(16), n2o: gasProduction(15) },
      resourceProductionPerUnit: { energy: resourceProduction(14) },
    },
  },
];
