import { Technology } from './types';
import { researchCost, generatorBaseCost, unlockCost, gasProduction, resourceProduction, generatorCostGrowth } from './scaling';

export const CHEMISTRY_TECHS: Technology[] = [
  {
    id: 'industrial_chemistry',
    name: 'Industrial Chemistry',
    branch: 'chemistry',
    kind: 'unlock',
    tier: 11,
    description: 'Systematic chemistry turns raw materials into whatever industry needs next.',
    icon: '⚗️',
    requires: ['chemical_industry'],
    cost: [{ resource: 'research', baseAmount: researchCost(11) }],
    costGrowth: 1,
    maxOwned: 1,
    effect: { researchMultiplier: 1.1 },
  },
  {
    id: 'ammonia',
    name: 'Ammonia',
    branch: 'chemistry',
    kind: 'generator',
    tier: 12,
    description: 'The Haber-Bosch process fixes nitrogen from thin air at industrial scale, feeding fertilizer plants worldwide.',
    icon: '🧪',
    requires: ['industrial_chemistry'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(12) }],
    costGrowth: generatorCostGrowth(12),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { n2o: gasProduction(10) * 0.4 },
      resourceProductionPerUnit: { energy: resourceProduction(12) },
    },
  },
  {
    id: 'refrigeration',
    name: 'Refrigeration',
    branch: 'chemistry',
    kind: 'generator',
    tier: 14,
    description: 'Mechanical cooling preserves food and comfort alike — using the first synthetic refrigerant gases.',
    icon: '🧊',
    requires: ['ammonia'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(14) }],
    costGrowth: generatorCostGrowth(14),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { fluorinated: gasProduction(9) * 0.05 },
      resourceProductionPerUnit: { energy: resourceProduction(13) },
    },
  },
  {
    id: 'cfcs',
    name: 'CFCs',
    branch: 'chemistry',
    kind: 'generator',
    tier: 16,
    description: 'Chlorofluorocarbons are cheap, stable, and everywhere — stable enough to drift into the stratosphere and eat ozone.',
    icon: '🌀',
    requires: ['refrigeration'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(16) }],
    costGrowth: generatorCostGrowth(16),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { fluorinated: gasProduction(11) * 0.08 },
      gasRemovalPerUnit: { o3: gasProduction(9) * 0.05 },
    },
  },
  {
    id: 'hfcs',
    name: 'HFCs',
    branch: 'chemistry',
    kind: 'generator',
    tier: 18,
    description: 'Hydrofluorocarbons replace ozone-eating CFCs — leaving the ozone layer alone, and warming the planet directly instead.',
    icon: '🌀',
    requires: ['cfcs'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(18) }],
    costGrowth: generatorCostGrowth(18),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { fluorinated: gasProduction(13) * 0.1 },
    },
  },
  {
    id: 'industrial_fluorinated_gases',
    name: 'Industrial Fluorinated Gases',
    branch: 'chemistry',
    kind: 'generator',
    tier: 20,
    description: 'PFCs and SF₆: some of the most potent, most persistent greenhouse gases ever synthesized.',
    icon: '☣️',
    requires: ['hfcs'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(20) }],
    costGrowth: generatorCostGrowth(20),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { fluorinated: gasProduction(15) * 0.12 },
    },
  },
  {
    id: 'advanced_chemical_manufacturing',
    name: 'Advanced Chemical Manufacturing',
    branch: 'chemistry',
    kind: 'multiplier',
    tier: 21,
    description: 'Automated, continuous chemical plants run every reaction in this branch simultaneously, everywhere.',
    icon: '🏭',
    requires: ['industrial_fluorinated_gases'],
    cost: [{ resource: 'energy', baseAmount: unlockCost(21) }],
    costGrowth: 1,
    maxOwned: 1,
    effect: { globalProductionMultiplier: 1.35 },
  },
];
