import { Technology } from './types';
import { researchCost, generatorBaseCost, unlockCost, gasProduction, resourceProduction, generatorCostGrowth } from './scaling';

export const DIGITAL_TECHS: Technology[] = [
  {
    id: 'computers',
    name: 'Computers',
    branch: 'digital',
    kind: 'unlock',
    tier: 20,
    description: 'Electronic computation replaces rooms full of clerks with a single humming cabinet.',
    icon: '💻',
    requires: ['mass_electrification'],
    cost: [{ resource: 'research', baseAmount: researchCost(20) }],
    costGrowth: 1,
    maxOwned: 1,
    effect: { researchMultiplier: 1.3 },
  },
  {
    id: 'internet',
    name: 'Internet',
    branch: 'digital',
    kind: 'multiplier',
    tier: 22,
    description: 'A global network lets every computer, factory, and market talk to every other, instantly.',
    icon: '🌐',
    requires: ['computers', 'global_supply_chains'],
    cost: [{ resource: 'energy', baseAmount: unlockCost(22) }],
    costGrowth: 1,
    maxOwned: 1,
    effect: { researchMultiplier: 1.4, globalProductionMultiplier: 1.1 },
  },
  {
    id: 'data_centers',
    name: 'Data Centers',
    branch: 'digital',
    kind: 'generator',
    tier: 23,
    description: 'Warehouses of servers run around the clock, drawing enormous power to keep the internet online.',
    icon: '🖥️',
    requires: ['internet'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(23) }],
    costGrowth: generatorCostGrowth(23),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(23) },
      resourceProductionPerUnit: { research: resourceProduction(21) },
    },
  },
  {
    id: 'cloud_computing',
    name: 'Cloud Computing',
    branch: 'digital',
    kind: 'generator',
    tier: 24,
    description: 'Computation-as-a-service means every phone and laptop can now offload work to a distant, power-hungry server farm.',
    icon: '☁️',
    requires: ['data_centers'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(24) }],
    costGrowth: generatorCostGrowth(24),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(24) },
      resourceProductionPerUnit: { research: resourceProduction(23) },
    },
  },
  {
    id: 'ai',
    name: 'AI',
    branch: 'digital',
    kind: 'generator',
    tier: 25,
    description: 'Machine learning models train on oceans of data, accelerating research — and power demand — together.',
    icon: '🤖',
    requires: ['cloud_computing'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(25) }],
    costGrowth: generatorCostGrowth(25),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(25) },
      resourceProductionPerUnit: { research: resourceProduction(24) },
    },
  },
  {
    id: 'mass_ai_infrastructure',
    name: 'Mass AI Infrastructure',
    branch: 'digital',
    kind: 'generator',
    tier: 26,
    description: 'Entire power grids are now built specifically to feed AI training clusters.',
    icon: '🧠',
    requires: ['ai'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(26) }],
    costGrowth: generatorCostGrowth(26),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(26) },
      resourceProductionPerUnit: { research: resourceProduction(25), energy: resourceProduction(24) },
    },
  },
  {
    id: 'hyperscale_data_centers',
    name: 'Hyperscale Data Centers',
    branch: 'digital',
    kind: 'multiplier',
    tier: 27,
    description: 'Campuses of data centers the size of small cities, humming continuously, forever.',
    icon: '🏢',
    requires: ['mass_ai_infrastructure'],
    cost: [{ resource: 'energy', baseAmount: unlockCost(27) }],
    costGrowth: 1,
    maxOwned: 1,
    effect: { globalProductionMultiplier: 1.6, researchMultiplier: 1.5 },
  },
];
