import { Technology } from './types';
import { unlockCost, generatorBaseCost, gasProduction, resourceProduction, generatorCostGrowth } from './scaling';

export const ENDGAME_TECHS: Technology[] = [
  {
    id: 'advanced_manufacturing',
    name: 'Advanced Manufacturing',
    branch: 'endgame',
    kind: 'multiplier',
    tier: 31,
    description: 'Robotic, self-replicating factories need no rest, no wages, and no limits.',
    icon: '🦾',
    requires: ['hyperscale_data_centers'],
    cost: [{ resource: 'energy', baseAmount: unlockCost(31) }],
    costGrowth: 1,
    maxOwned: 1,
    effect: { globalProductionMultiplier: 1.75 },
  },
  {
    id: 'orbital_industry',
    name: 'Orbital Industry',
    branch: 'endgame',
    kind: 'generator',
    tier: 32,
    description: 'Factories in orbit promise a cleaner future — powered by an awful lot of rocket fuel to get there.',
    icon: '🛰️',
    requires: ['advanced_manufacturing'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(32) }],
    costGrowth: generatorCostGrowth(32),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(32) },
      resourceProductionPerUnit: { energy: resourceProduction(30) },
    },
  },
  {
    id: 'moon_mining',
    name: 'Moon Mining',
    branch: 'endgame',
    kind: 'generator',
    tier: 34,
    description: 'Helium-3 and rare earths from the Moon feed an industry that never once slows down to ask why.',
    icon: '🌕',
    requires: ['orbital_industry'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(34) }],
    costGrowth: generatorCostGrowth(34),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(33) },
      resourceProductionPerUnit: { steel: resourceProduction(32), concrete: resourceProduction(32) },
    },
  },
  {
    id: 'planetary_industry',
    name: 'Planetary Industry',
    branch: 'endgame',
    kind: 'generator',
    tier: 36,
    description: 'Every remaining hectare of the planet\'s surface is now industrial infrastructure of some kind.',
    icon: '🌍',
    requires: ['moon_mining'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(36) }],
    costGrowth: generatorCostGrowth(36),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: {
        co2: gasProduction(36),
        ch4: gasProduction(33),
        n2o: gasProduction(33),
        fluorinated: gasProduction(30) * 0.1,
      },
      resourceProductionPerUnit: { energy: resourceProduction(34) },
    },
  },
  {
    id: 'dyson_swarm_prototype',
    name: 'Dyson Swarm Prototype',
    branch: 'endgame',
    kind: 'generator',
    tier: 38,
    description: 'The first panels of a solar-collecting swarm go up. Harvesting a star, warming a planet — a footnote by comparison.',
    icon: '☀️',
    requires: ['planetary_industry'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(38) }],
    costGrowth: generatorCostGrowth(38),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(38) },
      resourceProductionPerUnit: { energy: resourceProduction(36) },
    },
  },
  {
    id: 'stellar_energy',
    name: 'Stellar Energy',
    branch: 'endgame',
    kind: 'multiplier',
    tier: 40,
    description: 'Your civilization now answers its energy needs with a literal star. Ambition has entirely outrun restraint.',
    icon: '🌟',
    requires: ['dyson_swarm_prototype'],
    cost: [{ resource: 'energy', baseAmount: unlockCost(40) }],
    costGrowth: 1,
    maxOwned: 1,
    effect: { globalProductionMultiplier: 3 },
  },
];
