import { Technology } from './types';
import { researchCost, generatorBaseCost, unlockCost, gasProduction, resourceProduction, generatorCostGrowth } from './scaling';

export const INDUSTRY_TECHS: Technology[] = [
  {
    id: 'steam_engine',
    name: 'Steam Engine',
    branch: 'industry',
    kind: 'unlock',
    tier: 8,
    description: 'Boiling water under pressure yields mechanical power on demand. The industrial age begins.',
    icon: '⚙️',
    requires: ['iron'],
    cost: [{ resource: 'research', baseAmount: researchCost(8) }],
    costGrowth: 1,
    maxOwned: 1,
    effect: {},
  },
  {
    id: 'coal_mining',
    name: 'Coal Mining',
    branch: 'industry',
    kind: 'generator',
    tier: 9,
    description: 'Deep shafts pull ancient buried carbon out of the ground by the wagonload.',
    icon: '⛏️',
    requires: ['steam_engine'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(9) }],
    costGrowth: generatorCostGrowth(9),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(8) },
      resourceProductionPerUnit: { coal: resourceProduction(9) },
    },
  },
  {
    id: 'steam_locomotive',
    name: 'Steam Locomotive',
    branch: 'industry',
    kind: 'generator',
    tier: 10,
    description: 'Rail networks haul coal and freight faster than any road ever could.',
    icon: '🚂',
    requires: ['coal_mining'],
    cost: [
      { resource: 'energy', baseAmount: generatorBaseCost(10) },
      { resource: 'coal', baseAmount: generatorBaseCost(8) },
    ],
    costGrowth: generatorCostGrowth(10),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(10) },
      resourceProductionPerUnit: { energy: resourceProduction(9) },
    },
  },
  {
    id: 'factories',
    name: 'Factories',
    branch: 'industry',
    kind: 'generator',
    tier: 11,
    description: 'Coal-fired machinery under one roof outproduces a hundred workshops.',
    icon: '🏭',
    requires: ['steam_engine'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(11) }],
    costGrowth: generatorCostGrowth(11),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(11) },
      resourceProductionPerUnit: { energy: resourceProduction(11) },
    },
  },
  {
    id: 'steel_production',
    name: 'Steel Production',
    branch: 'industry',
    kind: 'generator',
    tier: 12,
    description: 'Bessemer converters turn iron into steel at unprecedented volume.',
    icon: '🔩',
    requires: ['coal_mining', 'iron'],
    cost: [
      { resource: 'energy', baseAmount: generatorBaseCost(12) },
      { resource: 'coal', baseAmount: generatorBaseCost(10) },
    ],
    costGrowth: generatorCostGrowth(12),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(12) },
      resourceProductionPerUnit: { steel: resourceProduction(11) },
    },
  },
  {
    id: 'cement_production',
    name: 'Cement Production',
    branch: 'industry',
    kind: 'generator',
    tier: 12,
    description: 'Roasting limestone into clinker is one of the most carbon-intensive processes in industry.',
    icon: '🧱',
    requires: ['factories'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(12) }],
    costGrowth: generatorCostGrowth(12),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(12) * 1.4 },
      resourceProductionPerUnit: { concrete: resourceProduction(11) },
    },
  },
  {
    id: 'industrial_furnaces',
    name: 'Industrial Furnaces',
    branch: 'industry',
    kind: 'generator',
    tier: 13,
    description: 'Ever-hotter furnaces process ore, scrap, and fuel around the clock.',
    icon: '🔥',
    requires: ['steel_production'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(13) }],
    costGrowth: generatorCostGrowth(13),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(13) },
      resourceProductionPerUnit: { steel: resourceProduction(12) },
    },
  },
  {
    id: 'mass_manufacturing',
    name: 'Mass Manufacturing',
    branch: 'industry',
    kind: 'multiplier',
    tier: 14,
    description: 'Standardized parts and assembly lines multiply every factory\'s output at once.',
    icon: '📦',
    requires: ['factories', 'cement_production'],
    cost: [{ resource: 'energy', baseAmount: unlockCost(14) }],
    costGrowth: 1,
    maxOwned: 1,
    effect: { globalProductionMultiplier: 1.25 },
  },
  {
    id: 'chemical_industry',
    name: 'Chemical Industry',
    branch: 'industry',
    kind: 'unlock',
    tier: 15,
    description: 'Industrial-scale chemistry opens doors nature never built.',
    icon: '⚗️',
    requires: ['mass_manufacturing'],
    cost: [{ resource: 'research', baseAmount: researchCost(15) }],
    costGrowth: 1,
    maxOwned: 1,
    effect: {},
  },
];
