import { Technology } from './types';
import { unlockCost, researchCost, generatorBaseCost, gasProduction, resourceProduction, generatorCostGrowth } from './scaling';

export const PRIMITIVE_TECHS: Technology[] = [
  {
    id: 'natural_fire',
    name: 'Natural Fire',
    branch: 'primitive',
    kind: 'unlock',
    tier: 0,
    description: 'Wildfires exist long before humans learn to use them. Observe how fire behaves.',
    icon: '🔥',
    requires: [],
    cost: [{ resource: 'research', baseAmount: researchCost(0) }],
    costGrowth: 1,
    maxOwned: 1,
    effect: {},
  },
  {
    id: 'controlled_fire',
    name: 'Controlled Fire',
    branch: 'primitive',
    kind: 'generator',
    tier: 1,
    description: 'Tame fire for warmth and light. Your first deliberate act of combustion — and emission.',
    icon: '🔥',
    requires: ['natural_fire'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(1) }],
    costGrowth: generatorCostGrowth(1),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(1) },
      resourceProductionPerUnit: { research: resourceProduction(1) * 0.5 },
    },
  },
  {
    id: 'cooking',
    name: 'Cooking',
    branch: 'primitive',
    kind: 'unlock',
    tier: 2,
    description: 'Cooked food yields more calories, freeing time for tool-making and ideas.',
    icon: '🍖',
    requires: ['controlled_fire'],
    cost: [{ resource: 'research', baseAmount: researchCost(2) }],
    costGrowth: 1,
    maxOwned: 1,
    effect: { researchMultiplier: 1.05 },
  },
  {
    id: 'charcoal',
    name: 'Charcoal',
    branch: 'primitive',
    kind: 'generator',
    tier: 3,
    description: 'Slow-burned wood yields a hotter, more portable fuel — civilization\'s first fuel stockpile.',
    icon: '🪵',
    requires: ['cooking'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(3) }],
    costGrowth: generatorCostGrowth(3),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(3) },
      resourceProductionPerUnit: { coal: resourceProduction(2) },
    },
  },
  {
    id: 'pottery',
    name: 'Pottery',
    branch: 'primitive',
    kind: 'unlock',
    tier: 3,
    description: 'Fired clay vessels let surplus food be stored — the seed of permanent settlement.',
    icon: '🏺',
    requires: ['cooking'],
    cost: [{ resource: 'research', baseAmount: researchCost(3) }],
    costGrowth: 1,
    maxOwned: 1,
    effect: { researchMultiplier: 1.05 },
  },
  {
    id: 'metalworking',
    name: 'Metalworking',
    branch: 'primitive',
    kind: 'unlock',
    tier: 4,
    description: 'Hot enough fires can shape metal. A new material age begins.',
    icon: '⚒️',
    requires: ['charcoal'],
    cost: [{ resource: 'research', baseAmount: researchCost(4) }],
    costGrowth: 1,
    maxOwned: 1,
    effect: {},
  },
  {
    id: 'bronze',
    name: 'Bronze',
    branch: 'primitive',
    kind: 'generator',
    tier: 5,
    description: 'Alloying copper and tin produces tools and weapons far tougher than stone.',
    icon: '🔔',
    requires: ['metalworking'],
    cost: [
      { resource: 'energy', baseAmount: generatorBaseCost(5) },
      { resource: 'coal', baseAmount: generatorBaseCost(3) },
    ],
    costGrowth: generatorCostGrowth(5),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(5) },
      resourceProductionPerUnit: { steel: resourceProduction(3) },
    },
  },
  {
    id: 'iron',
    name: 'Iron',
    branch: 'primitive',
    kind: 'generator',
    tier: 6,
    description: 'Hotter furnaces smelt iron — stronger, cheaper, and everywhere underfoot.',
    icon: '⛓️',
    requires: ['bronze'],
    cost: [
      { resource: 'energy', baseAmount: generatorBaseCost(6) },
      { resource: 'coal', baseAmount: generatorBaseCost(4) },
    ],
    costGrowth: generatorCostGrowth(6),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(6) },
      resourceProductionPerUnit: { steel: resourceProduction(4) },
    },
  },
  {
    id: 'early_agriculture',
    name: 'Early Agriculture',
    branch: 'primitive',
    kind: 'unlock',
    tier: 7,
    description: 'Deliberately planting and storing grain ends the nomadic era for good.',
    icon: '🌱',
    requires: ['pottery'],
    cost: [{ resource: 'research', baseAmount: researchCost(7) }],
    costGrowth: 1,
    maxOwned: 1,
    effect: { researchMultiplier: 1.1 },
  },
];
