package com.earthgame.idle.presentation.screens

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.produceState
import androidx.compose.runtime.getValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.sp
import com.earthgame.idle.presentation.components.GameCard
import com.earthgame.idle.presentation.theme.Dimens
import com.earthgame.idle.presentation.theme.gameColors
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

/**
 * The third-party notices, readable without unzipping the APK.
 *
 * The text is `THIRD_PARTY_NOTICES.txt` from the repository root, copied into
 * the app's assets at build time (see `BundleNoticesTask` in
 * `app/build.gradle.kts`) so the file on screen and the file in the repository
 * cannot disagree.
 *
 * It is read off the main thread and rendered a paragraph at a time: the file
 * is ~27 KB, which is a visible hitch as one `Text` and a scroll that has to
 * measure all of it up front.
 */
@Composable
fun LicensesScreen(
    contentPadding: PaddingValues,
    modifier: Modifier = Modifier,
) {
    val colors = gameColors
    val context = LocalContext.current

    val paragraphs by produceState(initialValue = emptyList<String>(), context) {
        value = withContext(Dispatchers.IO) {
            runCatching {
                context.assets.open(NOTICES_ASSET).bufferedReader().use { it.readText() }
                    .split("\n\n")
                    .map(String::trimEnd)
                    .filter(String::isNotBlank)
            }.getOrElse {
                // The asset is generated by the build, so a failure here means a
                // broken build rather than anything a player can act on. Say so
                // plainly instead of showing a stack trace or an empty screen.
                listOf(UNAVAILABLE)
            }
        }
    }

    LazyColumn(
        modifier = modifier.fillMaxWidth(),
        contentPadding = contentPadding,
        verticalArrangement = Arrangement.spacedBy(Dimens.CardSpacing),
    ) {
        if (paragraphs.isEmpty()) {
            item {
                Text(
                    text = "Loading licences…",
                    style = MaterialTheme.typography.bodySmall,
                    color = colors.textDim,
                )
            }
        }
        items(paragraphs) { paragraph ->
            GameCard {
                Text(
                    text = paragraph,
                    style = MaterialTheme.typography.labelSmall.copy(
                        fontFamily = FontFamily.Monospace,
                        fontSize = 10.sp,
                        lineHeight = 14.sp,
                    ),
                    color = colors.textDim,
                )
            }
        }
    }
}

private const val NOTICES_ASSET = "third_party_notices.txt"

private const val UNAVAILABLE =
    "The third-party notices could not be read from this build. They are also " +
        "published in the repository as THIRD_PARTY_NOTICES.txt."
