import { Technology } from './types';
import { generatorBaseCost, unlockCost, gasProduction, resourceProduction, generatorCostGrowth } from './scaling';

export const CONSTRUCTION_TECHS: Technology[] = [
  {
    id: 'concrete',
    name: 'Concrete',
    branch: 'construction',
    kind: 'generator',
    tier: 11,
    description: 'The most-used material on Earth, and one of the most carbon-intensive to produce.',
    icon: '🧱',
    requires: ['cement_production'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(11) }],
    costGrowth: generatorCostGrowth(11),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(11) },
      resourceProductionPerUnit: { concrete: resourceProduction(11) },
    },
  },
  {
    id: 'steel_buildings',
    name: 'Steel Buildings',
    branch: 'construction',
    kind: 'generator',
    tier: 13,
    description: 'Steel frames let buildings rise higher and faster than stone or wood ever allowed.',
    icon: '🏢',
    requires: ['steel_production', 'concrete'],
    cost: [{ resource: 'steel', baseAmount: generatorBaseCost(13) }],
    costGrowth: generatorCostGrowth(13),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(13) },
      resourceProductionPerUnit: { energy: resourceProduction(13) },
    },
  },
  {
    id: 'skyscrapers',
    name: 'Skyscrapers',
    branch: 'construction',
    kind: 'generator',
    tier: 15,
    description: 'Kilometer-scale towers pack a city\'s worth of energy demand onto one city block.',
    icon: '🏙️',
    requires: ['steel_buildings'],
    cost: [{ resource: 'steel', baseAmount: generatorBaseCost(15) }],
    costGrowth: generatorCostGrowth(15),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(15) },
      resourceProductionPerUnit: { energy: resourceProduction(15) },
    },
  },
  {
    id: 'airports',
    name: 'Airports',
    branch: 'construction',
    kind: 'generator',
    tier: 16,
    description: 'Runways and terminals sprawl outward to keep pace with air travel demand.',
    icon: '🛬',
    requires: ['concrete', 'commercial_aviation'],
    cost: [{ resource: 'concrete', baseAmount: generatorBaseCost(16) }],
    costGrowth: generatorCostGrowth(16),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(15) },
      resourceProductionPerUnit: { energy: resourceProduction(16) },
    },
  },
  {
    id: 'megacities',
    name: 'Megacities',
    branch: 'construction',
    kind: 'generator',
    tier: 17,
    description: 'Tens of millions of people, one continuous urban sprawl, running nonstop.',
    icon: '🌆',
    requires: ['skyscrapers'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(17) }],
    costGrowth: generatorCostGrowth(17),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(17), ch4: gasProduction(14) },
      resourceProductionPerUnit: { energy: resourceProduction(17) },
    },
  },
  {
    id: 'mega_infrastructure',
    name: 'Mega Infrastructure',
    branch: 'construction',
    kind: 'multiplier',
    tier: 18,
    description: 'Nationwide grids, ports, and transit systems bind cities into a single machine.',
    icon: '🏗️',
    requires: ['megacities', 'airports'],
    cost: [{ resource: 'energy', baseAmount: unlockCost(18) }],
    costGrowth: 1,
    maxOwned: 1,
    effect: { globalProductionMultiplier: 1.3 },
  },
  {
    id: 'global_urbanization',
    name: 'Global Urbanization',
    branch: 'construction',
    kind: 'multiplier',
    tier: 19,
    description: 'More than half the human race now lives in cities built this way. There is no going back.',
    icon: '🌍',
    requires: ['mega_infrastructure'],
    cost: [{ resource: 'energy', baseAmount: unlockCost(19) }],
    costGrowth: 1,
    maxOwned: 1,
    effect: { globalProductionMultiplier: 1.3, researchMultiplier: 1.2 },
  },
];
