import { Technology } from './types';
import { researchCost, generatorBaseCost, unlockCost, gasProduction, resourceProduction, generatorCostGrowth } from './scaling';

export const ELECTRICITY_TECHS: Technology[] = [
  {
    id: 'generator_dynamo',
    name: 'Generator',
    branch: 'electricity',
    kind: 'generator',
    tier: 9,
    description: 'Spinning a coil in a magnetic field conjures current from motion.',
    icon: '🔌',
    requires: ['steam_engine'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(9) }],
    costGrowth: generatorCostGrowth(9),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(7) },
      resourceProductionPerUnit: { energy: resourceProduction(9) },
    },
  },
  {
    id: 'coal_power_plant',
    name: 'Coal Power Plant',
    branch: 'electricity',
    kind: 'generator',
    tier: 11,
    description: 'Burning coal to boil water to spin turbines: the workhorse of the industrial grid.',
    icon: '🏭',
    requires: ['generator_dynamo', 'coal_mining'],
    cost: [
      { resource: 'energy', baseAmount: generatorBaseCost(11) },
      { resource: 'coal', baseAmount: generatorBaseCost(10) },
    ],
    costGrowth: generatorCostGrowth(11),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(11) },
      resourceProductionPerUnit: { energy: resourceProduction(12) },
    },
  },
  {
    id: 'grid_electricity',
    name: 'Grid Electricity',
    branch: 'electricity',
    kind: 'multiplier',
    tier: 12,
    description: 'A unified transmission grid lets every factory and home run on demand.',
    icon: '🗲',
    requires: ['coal_power_plant'],
    cost: [{ resource: 'energy', baseAmount: unlockCost(12) }],
    costGrowth: 1,
    maxOwned: 1,
    effect: { globalProductionMultiplier: 1.2 },
  },
  {
    id: 'hydroelectricity',
    name: 'Hydroelectricity',
    branch: 'electricity',
    kind: 'generator',
    tier: 13,
    description: 'Dammed rivers spin turbines with no combustion at all — clean, steady, huge.',
    icon: '🌊',
    requires: ['grid_electricity'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(13) }],
    costGrowth: generatorCostGrowth(13),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(6) },
      resourceProductionPerUnit: { energy: resourceProduction(13) },
    },
  },
  {
    id: 'gas_turbine',
    name: 'Gas Turbine',
    branch: 'electricity',
    kind: 'generator',
    tier: 13,
    description: 'Burning natural gas spins a turbine directly — quicker to build, dirtier than hydro.',
    icon: '🔥',
    requires: ['grid_electricity'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(13) }],
    costGrowth: generatorCostGrowth(13),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(12) },
      resourceProductionPerUnit: { energy: resourceProduction(13) },
    },
  },
  {
    id: 'coal_industrialization',
    name: 'Coal Industrialization',
    branch: 'electricity',
    kind: 'choice',
    tier: 14,
    description: 'Double down on cheap, abundant coal. Energy is plentiful; emissions skyrocket.',
    icon: '⚫',
    requires: ['coal_power_plant'],
    cost: [{ resource: 'energy', baseAmount: unlockCost(14) }],
    costGrowth: 1,
    maxOwned: 1,
    choiceGroup: 'energy_strategy',
    effect: { gasProductionMultiplier: { gas: 'co2', multiplier: 10 } },
  },
  {
    id: 'nuclear_industrialization',
    name: 'Nuclear Industrialization',
    branch: 'electricity',
    kind: 'choice',
    tier: 14,
    description: 'Invest in expensive, complex nuclear infrastructure for enormous clean output.',
    icon: '☢️',
    requires: ['coal_power_plant'],
    cost: [{ resource: 'energy', baseAmount: unlockCost(14) * 1.5 }],
    costGrowth: 1,
    maxOwned: 1,
    choiceGroup: 'energy_strategy',
    effect: { resourceProductionMultiplier: { resource: 'energy', multiplier: 5 } },
  },
  {
    id: 'nuclear_power',
    name: 'Nuclear Power',
    branch: 'electricity',
    kind: 'generator',
    tier: 15,
    description: 'Splitting atoms releases enormous energy with almost no direct emissions.',
    icon: '☢️',
    requires: ['grid_electricity'],
    cost: [
      { resource: 'energy', baseAmount: generatorBaseCost(15) },
      { resource: 'steel', baseAmount: generatorBaseCost(13) },
    ],
    costGrowth: generatorCostGrowth(15),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(4) },
      resourceProductionPerUnit: { energy: resourceProduction(15) },
    },
  },
  {
    id: 'supercritical_coal',
    name: 'Supercritical Coal',
    branch: 'electricity',
    kind: 'generator',
    tier: 16,
    description: 'Higher pressures and temperatures wring more power from every lump of coal — and more CO₂.',
    icon: '🏭',
    requires: ['coal_power_plant'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(16) }],
    costGrowth: generatorCostGrowth(16),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(16) },
      resourceProductionPerUnit: { energy: resourceProduction(16) },
    },
  },
  {
    id: 'combined_cycle_gas',
    name: 'Combined Cycle Gas',
    branch: 'electricity',
    kind: 'generator',
    tier: 16,
    description: 'Pairing a gas turbine with a steam turbine squeezes far more energy from the same fuel.',
    icon: '🔧',
    requires: ['gas_turbine'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(16) }],
    costGrowth: generatorCostGrowth(16),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(15) },
      resourceProductionPerUnit: { energy: resourceProduction(17) },
    },
  },
  {
    id: 'mass_electrification',
    name: 'Mass Electrification',
    branch: 'electricity',
    kind: 'multiplier',
    tier: 17,
    description: 'Every corner of civilization now runs on the grid. Output compounds everywhere.',
    icon: '⚡',
    requires: ['nuclear_power', 'combined_cycle_gas'],
    cost: [{ resource: 'energy', baseAmount: unlockCost(17) }],
    costGrowth: 1,
    maxOwned: 1,
    effect: { globalProductionMultiplier: 1.3 },
  },
];
