import { Technology } from './types';
import { generatorBaseCost, gasProduction, resourceProduction, generatorCostGrowth } from './scaling';

export const FOSSIL_FUEL_TECHS: Technology[] = [
  {
    id: 'oil_drilling',
    name: 'Oil Drilling',
    branch: 'fossilFuels',
    kind: 'generator',
    tier: 9,
    description: 'Derricks tap ancient buried hydrocarbons — denser energy than coal, easier to move.',
    icon: '🛢️',
    requires: ['steam_engine'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(9) }],
    costGrowth: generatorCostGrowth(9),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(7) },
      resourceProductionPerUnit: { oil: resourceProduction(9) },
    },
  },
  {
    id: 'oil_refinery',
    name: 'Oil Refinery',
    branch: 'fossilFuels',
    kind: 'generator',
    tier: 10,
    description: 'Cracking crude into fuel and feedstock unlocks everything downstream of petroleum.',
    icon: '🏭',
    requires: ['oil_drilling'],
    cost: [
      { resource: 'energy', baseAmount: generatorBaseCost(10) },
      { resource: 'oil', baseAmount: generatorBaseCost(9) },
    ],
    costGrowth: generatorCostGrowth(10),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(10) },
      resourceProductionPerUnit: { energy: resourceProduction(10) },
    },
  },
  {
    id: 'petrochemicals',
    name: 'Petrochemicals',
    branch: 'fossilFuels',
    kind: 'unlock',
    tier: 12,
    description: 'Oil becomes plastic, solvent, and synthetic fiber. Petroleum touches everything now.',
    icon: '⚗️',
    requires: ['oil_refinery'],
    cost: [{ resource: 'research', baseAmount: generatorBaseCost(12) * 0.4 }],
    costGrowth: 1,
    maxOwned: 1,
    effect: { researchMultiplier: 1.1 },
  },
  {
    id: 'natural_gas',
    name: 'Natural Gas',
    branch: 'fossilFuels',
    kind: 'generator',
    tier: 12,
    description: 'Gas burns cleaner than coal, per unit of energy — though it still adds up fast at scale.',
    icon: '🔥',
    requires: ['oil_drilling'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(12) }],
    costGrowth: generatorCostGrowth(12),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(11) },
      resourceProductionPerUnit: { energy: resourceProduction(12) },
    },
  },
  {
    id: 'fracking',
    name: 'Fracking',
    branch: 'fossilFuels',
    kind: 'generator',
    tier: 14,
    description: 'Shattering deep shale releases trapped gas — and lets a fair amount of methane leak straight to the air.',
    icon: '💥',
    requires: ['natural_gas'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(14) }],
    costGrowth: generatorCostGrowth(14),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(13), ch4: gasProduction(11) * 0.4 },
      resourceProductionPerUnit: { oil: resourceProduction(13) },
    },
  },
  {
    id: 'offshore_drilling',
    name: 'Offshore Drilling',
    branch: 'fossilFuels',
    kind: 'generator',
    tier: 15,
    description: 'Platforms far out to sea reach reserves no derrick on land ever could.',
    icon: '🌊',
    requires: ['oil_refinery'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(15) }],
    costGrowth: generatorCostGrowth(15),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(14) },
      resourceProductionPerUnit: { oil: resourceProduction(15) },
    },
  },
  {
    id: 'oil_sands',
    name: 'Oil Sands',
    branch: 'fossilFuels',
    kind: 'generator',
    tier: 16,
    description: 'Extracting oil from tar-thick sand takes enormous heat and water — and emits accordingly.',
    icon: '🏜️',
    requires: ['offshore_drilling'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(16) }],
    costGrowth: generatorCostGrowth(16),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(16) * 1.3 },
      resourceProductionPerUnit: { oil: resourceProduction(16) },
    },
  },
  {
    id: 'coal_mega_mining',
    name: 'Coal Mega-Mining',
    branch: 'fossilFuels',
    kind: 'generator',
    tier: 17,
    description: 'Whole mountains are leveled for the coal seams beneath them.',
    icon: '⛏️',
    requires: ['coal_mining', 'oil_sands'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(17) }],
    costGrowth: generatorCostGrowth(17),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(17) },
      resourceProductionPerUnit: { coal: resourceProduction(17) },
    },
  },
];
