import { Technology } from './types';
import { researchCost, generatorBaseCost, unlockCost, gasProduction, resourceProduction, generatorCostGrowth } from './scaling';

export const GLOBALIZATION_TECHS: Technology[] = [
  {
    id: 'international_trade',
    name: 'International Trade',
    branch: 'globalization',
    kind: 'unlock',
    tier: 17,
    description: 'Nations specialize and trade at scale, wiring the world\'s economies together.',
    icon: '🌐',
    requires: ['container_ships'],
    cost: [{ resource: 'research', baseAmount: researchCost(17) }],
    costGrowth: 1,
    maxOwned: 1,
    effect: { researchMultiplier: 1.15 },
  },
  {
    id: 'containerization',
    name: 'Containerization',
    branch: 'globalization',
    kind: 'generator',
    tier: 18,
    description: 'Standardized shipping containers make loading and moving goods almost frictionless — so the world moves a lot more of them.',
    icon: '📦',
    requires: ['international_trade'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(18) }],
    costGrowth: generatorCostGrowth(18),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(17) },
      resourceProductionPerUnit: { energy: resourceProduction(18) },
    },
  },
  {
    id: 'global_supply_chains',
    name: 'Global Supply Chains',
    branch: 'globalization',
    kind: 'multiplier',
    tier: 19,
    description: 'Parts cross a dozen borders before a product is finished. Efficiency has no geography left.',
    icon: '🔗',
    requires: ['containerization', 'global_logistics'],
    cost: [{ resource: 'energy', baseAmount: unlockCost(19) }],
    costGrowth: 1,
    maxOwned: 1,
    effect: { globalProductionMultiplier: 1.25 },
  },
  {
    id: 'consumer_economy',
    name: 'Consumer Economy',
    branch: 'globalization',
    kind: 'generator',
    tier: 20,
    description: 'Mass production meets mass marketing: an economy built on buying more, replacing sooner, discarding faster.',
    icon: '🛍️',
    requires: ['global_supply_chains'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(20) }],
    costGrowth: generatorCostGrowth(20),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(20), ch4: gasProduction(16) },
      resourceProductionPerUnit: { energy: resourceProduction(20) },
    },
  },
  {
    id: 'global_aviation_networks',
    name: 'Global Aviation Networks',
    branch: 'globalization',
    kind: 'generator',
    tier: 21,
    description: 'Hub airports link every major city on the planet with a same-day flight.',
    icon: '🛩️',
    requires: ['commercial_aviation'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(21) }],
    costGrowth: generatorCostGrowth(21),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(21), o3: gasProduction(13) * 0.2 },
      resourceProductionPerUnit: { energy: resourceProduction(21) },
    },
  },
  {
    id: '247_manufacturing',
    name: '24/7 Manufacturing',
    branch: 'globalization',
    kind: 'generator',
    tier: 22,
    description: 'Factories across every time zone mean production never actually stops, anywhere, ever.',
    icon: '🏭',
    requires: ['consumer_economy'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(22) }],
    costGrowth: generatorCostGrowth(22),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(22) },
      resourceProductionPerUnit: { energy: resourceProduction(22) },
    },
  },
  {
    id: 'megacorporations',
    name: 'Megacorporations',
    branch: 'globalization',
    kind: 'multiplier',
    tier: 23,
    description: 'A handful of firms now operate at the scale of nations, and answer to no single one.',
    icon: '🏢',
    requires: ['247_manufacturing', 'global_aviation_networks'],
    cost: [{ resource: 'energy', baseAmount: unlockCost(23) }],
    costGrowth: 1,
    maxOwned: 1,
    effect: { globalProductionMultiplier: 1.5, researchMultiplier: 1.3 },
  },
];
