import { Technology } from './types';
import { unlockCost, researchCost, generatorBaseCost, gasProduction, resourceProduction, generatorCostGrowth } from './scaling';

/**
 * The opening of the game. Every civilization begins with a single burning
 * thing and works its way up: fire is both the first energy source and the
 * first emission, so the branch doubles as the tutorial for the whole
 * economy — every generator here turns fuel into Energy, and pays for it in
 * carbon.
 */
export const PRIMITIVE_TECHS: Technology[] = [
  {
    id: 'natural_fire',
    name: 'Natural Fire',
    branch: 'primitive',
    kind: 'generator',
    tier: 0,
    description:
      'A lightning-struck tree, still smouldering. You keep the embers alive, and they keep giving off heat — your very first source of Energy.',
    icon: '🔥',
    requires: [],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(0) }],
    costGrowth: generatorCostGrowth(0),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(0) },
      resourceProductionPerUnit: { energy: resourceProduction(0) },
    },
  },
  {
    id: 'controlled_fire',
    name: 'Controlled Fire',
    branch: 'primitive',
    kind: 'generator',
    tier: 1,
    description:
      'A hearth you can light at will, rather than one you happen to find. Warmth, light, and the first fuel you burn on purpose.',
    icon: '🪔',
    requires: ['natural_fire'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(1) }],
    costGrowth: generatorCostGrowth(1),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(1) },
      resourceProductionPerUnit: { energy: resourceProduction(1), research: resourceProduction(0) * 0.5 },
    },
  },
  {
    id: 'cooking',
    name: 'Cooking',
    branch: 'primitive',
    kind: 'unlock',
    tier: 2,
    description: 'Cooked food yields more calories, freeing time for tool-making and ideas.',
    icon: '🍖',
    requires: ['controlled_fire'],
    cost: [{ resource: 'research', baseAmount: researchCost(2) }],
    costGrowth: 1,
    maxOwned: 1,
    effect: { researchMultiplier: 1.15 },
  },
  {
    id: 'charcoal',
    name: 'Charcoal Kiln',
    branch: 'primitive',
    kind: 'generator',
    tier: 3,
    description: 'Slow-burned wood yields a hotter, more portable fuel — civilization\'s first fuel stockpile.',
    icon: '🪵',
    requires: ['cooking'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(3) }],
    costGrowth: generatorCostGrowth(3),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(3) },
      resourceProductionPerUnit: { energy: resourceProduction(2), coal: resourceProduction(2) },
    },
  },
  {
    id: 'pottery',
    name: 'Pottery',
    branch: 'primitive',
    kind: 'unlock',
    tier: 3,
    description: 'Fired clay vessels let surplus food be stored — the seed of permanent settlement.',
    icon: '🏺',
    requires: ['cooking'],
    cost: [{ resource: 'research', baseAmount: researchCost(3) }],
    costGrowth: 1,
    maxOwned: 1,
    effect: { researchMultiplier: 1.15 },
  },
  {
    id: 'metalworking',
    name: 'Metalworking',
    branch: 'primitive',
    kind: 'unlock',
    tier: 4,
    description: 'Hot enough fires can shape metal. A new material age begins.',
    icon: '⚒️',
    requires: ['charcoal'],
    cost: [{ resource: 'research', baseAmount: researchCost(4) }],
    costGrowth: 1,
    maxOwned: 1,
    effect: {},
  },
  {
    id: 'bronze',
    name: 'Bronze Smelting',
    branch: 'primitive',
    kind: 'generator',
    tier: 5,
    description: 'Alloying copper and tin produces tools and weapons far tougher than stone.',
    icon: '🔔',
    requires: ['metalworking'],
    cost: [
      { resource: 'energy', baseAmount: generatorBaseCost(5) },
      { resource: 'coal', baseAmount: generatorBaseCost(3) },
    ],
    costGrowth: generatorCostGrowth(5),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(5) },
      resourceProductionPerUnit: { energy: resourceProduction(4), steel: resourceProduction(3) },
    },
  },
  {
    id: 'iron',
    name: 'Iron Smelting',
    branch: 'primitive',
    kind: 'generator',
    tier: 6,
    description: 'Hotter furnaces smelt iron — stronger, cheaper, and everywhere underfoot.',
    icon: '⛓️',
    requires: ['bronze'],
    cost: [
      { resource: 'energy', baseAmount: generatorBaseCost(6) },
      { resource: 'coal', baseAmount: generatorBaseCost(4) },
    ],
    costGrowth: generatorCostGrowth(6),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(6) },
      resourceProductionPerUnit: { energy: resourceProduction(5), steel: resourceProduction(4) },
    },
  },
  {
    id: 'the_wheel',
    name: 'The Wheel',
    branch: 'primitive',
    kind: 'multiplier',
    tier: 6,
    description: 'Everything you already do, done with less effort. +25% to all production.',
    icon: '☸️',
    requires: ['pottery', 'metalworking'],
    cost: [{ resource: 'energy', baseAmount: unlockCost(6) }],
    costGrowth: 1,
    maxOwned: 1,
    effect: { globalProductionMultiplier: 1.25 },
  },
  {
    id: 'early_agriculture',
    name: 'Early Agriculture',
    branch: 'primitive',
    kind: 'unlock',
    tier: 7,
    description: 'Deliberately planting and storing grain ends the nomadic era for good.',
    icon: '🌱',
    requires: ['pottery'],
    cost: [{ resource: 'research', baseAmount: researchCost(7) }],
    costGrowth: 1,
    maxOwned: 1,
    effect: { researchMultiplier: 1.2 },
  },
];
