import { Technology } from './types';
import { generatorBaseCost, unlockCost, gasProduction, resourceProduction, generatorCostGrowth } from './scaling';

export const TRANSPORTATION_TECHS: Technology[] = [
  {
    id: 'horse_and_cart',
    name: 'Horse & Cart',
    branch: 'transportation',
    kind: 'generator',
    tier: 8,
    description: 'Domesticated draft animals move goods faster than any human back.',
    icon: '🐴',
    requires: ['early_agriculture'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(8) }],
    costGrowth: generatorCostGrowth(8),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { ch4: gasProduction(6) * 0.3 },
      resourceProductionPerUnit: { research: resourceProduction(7) },
    },
  },
  {
    id: 'steam_vehicle',
    name: 'Steam Vehicle',
    branch: 'transportation',
    kind: 'generator',
    tier: 10,
    description: 'Self-propelled steam carriages replace the horse on the open road.',
    icon: '🚃',
    requires: ['steam_engine'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(10) }],
    costGrowth: generatorCostGrowth(10),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(9) },
      resourceProductionPerUnit: { energy: resourceProduction(9) },
    },
  },
  {
    id: 'automobile',
    name: 'Automobile',
    branch: 'transportation',
    kind: 'generator',
    tier: 12,
    description: 'The internal combustion engine puts a private vehicle within reach of ordinary people.',
    icon: '🚗',
    requires: ['oil_refinery'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(12) }],
    costGrowth: generatorCostGrowth(12),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(11) },
      resourceProductionPerUnit: { energy: resourceProduction(11) },
    },
  },
  {
    id: 'mass_production_cars',
    name: 'Mass Production Cars',
    branch: 'transportation',
    kind: 'generator',
    tier: 13,
    description: 'Assembly lines put a car in every driveway, and exhaust over every street.',
    icon: '🚙',
    requires: ['automobile', 'factories'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(13) }],
    costGrowth: generatorCostGrowth(13),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(13) },
      resourceProductionPerUnit: { energy: resourceProduction(12) },
    },
  },
  {
    id: 'diesel_engine',
    name: 'Diesel Engine',
    branch: 'transportation',
    kind: 'generator',
    tier: 13,
    description: 'More torque, more efficiency, more soot — diesel becomes the standard for heavy hauling.',
    icon: '⛽',
    requires: ['oil_refinery'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(13) }],
    costGrowth: generatorCostGrowth(13),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(12) },
      resourceProductionPerUnit: { energy: resourceProduction(13) },
    },
  },
  {
    id: 'trucks',
    name: 'Trucks',
    branch: 'transportation',
    kind: 'generator',
    tier: 14,
    description: 'Diesel freight trucks connect factories to shelves without needing a railway.',
    icon: '🚚',
    requires: ['diesel_engine'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(14) }],
    costGrowth: generatorCostGrowth(14),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(14) },
      resourceProductionPerUnit: { energy: resourceProduction(14) },
    },
  },
  {
    id: 'highways',
    name: 'Highways',
    branch: 'transportation',
    kind: 'multiplier',
    tier: 14,
    description: 'Paved, limited-access roads let vehicles move faster, farther, and in far greater numbers.',
    icon: '🛣️',
    requires: ['mass_production_cars'],
    cost: [{ resource: 'concrete', baseAmount: unlockCost(14) }],
    costGrowth: 1,
    maxOwned: 1,
    effect: { branchProductionMultiplier: { branch: 'transportation', multiplier: 1.25 } },
  },
  {
    id: 'jet_aircraft',
    name: 'Jet Aircraft',
    branch: 'transportation',
    kind: 'generator',
    tier: 15,
    description: 'Turbojets cross continents in hours, burning fuel at high altitude where it matters more.',
    icon: '✈️',
    requires: ['diesel_engine', 'petrochemicals'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(15) }],
    costGrowth: generatorCostGrowth(15),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(15), n2o: gasProduction(11) * 0.15 },
      resourceProductionPerUnit: { energy: resourceProduction(15) },
    },
  },
  {
    id: 'commercial_aviation',
    name: 'Commercial Aviation',
    branch: 'transportation',
    kind: 'generator',
    tier: 16,
    description: 'Air travel becomes routine, not remarkable. The skies fill with contrails.',
    icon: '🛫',
    requires: ['jet_aircraft'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(16) }],
    costGrowth: generatorCostGrowth(16),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(16), o3: gasProduction(10) * 0.2 },
      resourceProductionPerUnit: { energy: resourceProduction(16) },
    },
  },
  {
    id: 'container_ships',
    name: 'Container Ships',
    branch: 'transportation',
    kind: 'generator',
    tier: 16,
    description: 'Standardized steel boxes on diesel-burning giants move the world\'s goods across oceans.',
    icon: '🚢',
    requires: ['oil_refinery'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(16) }],
    costGrowth: generatorCostGrowth(16),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(15) },
      resourceProductionPerUnit: { energy: resourceProduction(17) },
    },
  },
  {
    id: 'global_logistics',
    name: 'Global Logistics',
    branch: 'transportation',
    kind: 'multiplier',
    tier: 17,
    description: 'Trucks, trains, ships, and planes now form one coordinated worldwide supply machine.',
    icon: '🌐',
    requires: ['container_ships', 'trucks'],
    cost: [{ resource: 'energy', baseAmount: unlockCost(17) }],
    costGrowth: 1,
    maxOwned: 1,
    effect: { globalProductionMultiplier: 1.2 },
  },
  {
    id: 'supersonic_aviation',
    name: 'Supersonic Aviation',
    branch: 'transportation',
    kind: 'generator',
    tier: 19,
    description: 'Breaking the sound barrier for a business flight, at an enormous fuel and emissions premium.',
    icon: '🚀',
    requires: ['commercial_aviation'],
    cost: [{ resource: 'energy', baseAmount: generatorBaseCost(19) }],
    costGrowth: generatorCostGrowth(19),
    maxOwned: Infinity,
    effect: {
      gasProductionPerUnit: { co2: gasProduction(19), n2o: gasProduction(14) * 0.2 },
      resourceProductionPerUnit: { energy: resourceProduction(18) },
    },
  },
];
